"""6502 opcode lookup tables.

Two parallel 256-entry tables indexed by opcode:

- `ADDRESSING_MODE_TABLE[opcode]` → one of the `ADDR_*` constants below.
- `CYCLE_TABLE[opcode]`           → base cycle count for the opcode
  (does NOT include the +1 page-crossing penalty or +1/+2 branch penalty;
  those are computed at runtime in `cpu.m6502`).

Both tables are the standard NMOS 6502 set. Undocumented opcodes are mapped
to plausible cycle counts but their behaviour is NOT implemented in P1 — see
PORTING_PLAN.md §5 P1f.
"""

import jax.numpy as jnp

# Addressing modes
ADDR_IMPLIED      = 0
ADDR_IMMEDIATE    = 1
ADDR_ZERO         = 2
ADDR_ZERO_X       = 3
ADDR_ZERO_Y       = 4
ADDR_ABSOLUTE     = 5
ADDR_ABSOLUTE_X   = 6
ADDR_ABSOLUTE_Y   = 7
ADDR_INDIRECT     = 8
ADDR_INDIRECT_X   = 9
ADDR_INDIRECT_Y   = 10
ADDR_RELATIVE     = 11

ADDRESSING_MODE_TABLE = jnp.array([
    # 0x0?
    ADDR_IMPLIED, ADDR_INDIRECT_X, ADDR_IMPLIED, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0x1?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X,
    # 0x2?
    ADDR_ABSOLUTE, ADDR_INDIRECT_X, ADDR_IMPLIED, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0x3?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X,
    # 0x4?
    ADDR_IMPLIED, ADDR_INDIRECT_X, ADDR_IMPLIED, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0x5?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X,
    # 0x6?
    ADDR_IMPLIED, ADDR_INDIRECT_X, ADDR_IMPLIED, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_INDIRECT, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0x7?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X,
    # 0x8?
    ADDR_IMMEDIATE, ADDR_INDIRECT_X, ADDR_IMMEDIATE, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0x9?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_Y, ADDR_ZERO_Y,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_Y, ADDR_ABSOLUTE_Y,
    # 0xA?
    ADDR_IMMEDIATE, ADDR_INDIRECT_X, ADDR_IMMEDIATE, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0xB?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_Y, ADDR_ZERO_Y,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_Y, ADDR_ABSOLUTE_Y,
    # 0xC?
    ADDR_IMMEDIATE, ADDR_INDIRECT_X, ADDR_IMMEDIATE, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0xD?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X,
    # 0xE?
    ADDR_IMMEDIATE, ADDR_INDIRECT_X, ADDR_IMMEDIATE, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0xF?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X,
], dtype=jnp.uint8)


CYCLE_TABLE = jnp.array([
    7, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 4, 4, 6, 6,  # 0
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,  # 1
    6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 4, 4, 6, 6,  # 2
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,  # 3
    6, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 3, 4, 6, 6,  # 4
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,  # 5
    6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 5, 4, 6, 6,  # 6
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,  # 7
    2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 4, 4,  # 8
    2, 6, 2, 6, 4, 4, 4, 4, 2, 5, 2, 5, 5, 5, 5, 5,  # 9
    2, 6, 2, 6, 3, 3, 3, 4, 2, 2, 2, 2, 4, 4, 4, 4,  # A
    2, 5, 2, 5, 4, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 4,  # B
    2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6,  # C
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,  # D
    2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6,  # E
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,  # F
], dtype=jnp.uint8)


# 6502 status register bit masks
FLAG_N = 0x80  # negative
FLAG_V = 0x40  # overflow
FLAG_U = 0x20  # unused, always 1
FLAG_B = 0x10  # break
FLAG_D = 0x08  # decimal (ignored on the 2A03; honoured on the stock 6502)
FLAG_I = 0x04  # interrupt disable
FLAG_Z = 0x02  # zero
FLAG_C = 0x01  # carry
