"""PXC2 — jaxtari ≡ jutari direct cross-check.

PXC1 / PXC1-x established that the same 10 RAM bytes diverge
identically in jaxtari and jutari when both are checked against the
xitari reference trace. PXC2 makes that *implicit* equality
*explicit*: drive both jaxtari (live) and jutari (a pre-committed
trace dump under `tools/fixtures/traces/`) with the same action
sequence and assert their per-frame RAM is byte-exact identical.

A regression where one port "improves" by closing some of the 10-byte
gap without the other port matching it would fail this test — the
divergence pattern is intentionally locked in until PXC1-x round 5
closes it on both sides simultaneously.

As of the **PXC2 Breakout extension**, the test is parametric over
multiple ROMs. Each ROM contributes:

  * a jutari fixture file (`tools/fixtures/traces/<rom>_noop_10_jutari.jsonl`)
    generated by `tools/jutari_trace_dump.jl`,
  * an xitari reference trace (`tools/fixtures/traces/<rom>_noop_10.jsonl`)
    generated by `tools/trace_dump`,
  * an expected jaxtari-vs-xitari divergence count on the last frame
    (the PXC1-x round 1 outcome — kept as a regression guard).

Refresh recipe: if you change *either* engine in a way that
legitimately moves a divergence count, **update both fixtures in
the same commit** (regenerate both engines' traces, update the
expected count) so PXC2 stays lock-step.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import NamedTuple

import numpy as np
import pytest

from jaxtari.env.stella_environment import StellaEnvironment


_REPO_ROOT = Path(__file__).resolve().parents[2]


class _RomCase(NamedTuple):
    """One row in the PXC2 cross-check table."""
    name: str                              # short id used in test ids
    rom_filename: str                      # under xitari/roms/
    xitari_trace: str                      # under tools/fixtures/traces/
    jutari_trace: str                      # under tools/fixtures/traces/
    expected_xitari_divergence: int        # bytes that differ from xitari on last frame


# Canonical cross-check ROMs. To add a new one:
#   1. Write a tools/fixtures/actions/<name>.txt action file.
#   2. Generate the xitari trace:
#        ./tools/trace_dump --rom xitari/roms/<rom> \
#            --actions tools/fixtures/actions/<name>.txt \
#            > tools/fixtures/traces/<name>.jsonl
#   3. Generate the jutari trace:
#        julia --project=jutari tools/jutari_trace_dump.jl \
#            --rom xitari/roms/<rom> \
#            --trace tools/fixtures/traces/<name>.jsonl \
#            --out  tools/fixtures/traces/<name>_jutari.jsonl
#   4. Run this file once with a placeholder `expected_xitari_divergence`
#      = -1; the third test prints the observed count via a pytest.skip
#      message. Plug that number into the case row and re-run.
_PXC2_CASES = (
    _RomCase(
        name="pong_noop_10",
        rom_filename="pong.bin",
        xitari_trace="pong_noop_10.jsonl",
        jutari_trace="pong_noop_10_jutari.jsonl",
        expected_xitari_divergence=10,     # PXC1-x round 1 outcome
    ),
    _RomCase(
        name="breakout_noop_10",
        rom_filename="breakout.bin",
        xitari_trace="breakout_noop_10.jsonl",
        jutari_trace="breakout_noop_10_jutari.jsonl",
        expected_xitari_divergence=4,      # PXC2-Breakout (round 4.5 era)
    ),
    _RomCase(
        # Joystick-only game (no `Controller.Left/Right` props for this
        # MD5 → defaults to Joystick). Observed divergence: **0 bytes**
        # — jaxtari matches xitari bit-perfectly. This is the strong
        # confirmation of the round 4.5 finding: the residual
        # pong/breakout divergence is *paddle-INPT-specific*, not a
        # general 6502 emulation gap. Any ROM that doesn't read
        # INPT0-3 is already at conformance parity.
        name="space_invaders_noop_10",
        rom_filename="space_invaders.bin",
        xitari_trace="space_invaders_noop_10.jsonl",
        jutari_trace="space_invaders_noop_10_jutari.jsonl",
        expected_xitari_divergence=0,
    ),
    _RomCase(
        # Second joystick-only witness (after Space Invaders). Boots
        # cleanly in both ports (unlike Asteroids → game-over-at-boot
        # and Q*Bert → jutari boot hang, see task #52). Observed
        # divergence: **19 bytes** — the "joystick ROMs are bit-perfect"
        # generalization from Space Invaders is therefore *too strong*.
        # The correct statement: SI happens to read very little
        # bus-noise-affected state during boot; Pitfall reads more
        # (probably INPT5 trigger + RIOT timer reads), so it inherits
        # the same root cause as Pong (data_bus_state drift from
        # missing 6502 internal-cycle bus exposures) but in different
        # cells. jaxtari ≡ jutari still holds (PXC2 invariant: both
        # ports diverge from xitari in the same way).
        name="pitfall_noop_10",
        rom_filename="pitfall.bin",
        xitari_trace="pitfall_noop_10.jsonl",
        jutari_trace="pitfall_noop_10_jutari.jsonl",
        expected_xitari_divergence=19,
    ),
    _RomCase(
        # Joystick-only ROM. Observed divergence: 4 bytes — same as
        # Breakout. Sits in the low-RIOT-poll range with paddle-INPT
        # impact close to zero (joystick) but enough bus-noise reads
        # to manifest a few cells.
        name="seaquest_noop_10",
        rom_filename="seaquest.bin",
        xitari_trace="seaquest_noop_10.jsonl",
        jutari_trace="seaquest_noop_10_jutari.jsonl",
        expected_xitari_divergence=4,
    ),
    _RomCase(
        # Joystick-only ROM. Observed divergence: **47 bytes** — the
        # highest among the 6 PXC2 cases by a wide margin. Enduro's
        # boot does substantial timer / switch polling (it's a long
        # race game with intricate setup) so the data_bus_state drift
        # chains into many RAM cells. Same root cause as the others
        # — just a more extreme manifestation.
        name="enduro_noop_10",
        rom_filename="enduro.bin",
        xitari_trace="enduro_noop_10.jsonl",
        jutari_trace="enduro_noop_10_jutari.jsonl",
        expected_xitari_divergence=47,
    ),
)


def _rom_path(case: _RomCase) -> Path:
    return _REPO_ROOT / "xitari" / "roms" / case.rom_filename


def _xitari_trace_path(case: _RomCase) -> Path:
    return _REPO_ROOT / "tools" / "fixtures" / "traces" / case.xitari_trace


def _jutari_trace_path(case: _RomCase) -> Path:
    return _REPO_ROOT / "tools" / "fixtures" / "traces" / case.jutari_trace


def _have_fixtures(case: _RomCase) -> bool:
    return (_rom_path(case).is_file()
            and _xitari_trace_path(case).is_file()
            and _jutari_trace_path(case).is_file())


def _skip_reason(case: _RomCase) -> str:
    return (
        f"PXC2 fixtures missing for {case.name} — regenerate via the "
        f"recipe in this file's docstring."
    )


def _load_actions(trace_path: Path) -> list[int]:
    out: list[int] = []
    with open(trace_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            out.append(int(json.loads(line)["action"]))
    return out


def _load_ram_per_frame(trace_path: Path) -> list[bytes]:
    rams: list[bytes] = []
    with open(trace_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            rams.append(bytes.fromhex(rec["ram"]))
    return rams


def _jaxtari_ram_per_frame(rom_bytes: bytes, actions: list[int]) -> list[bytes]:
    rom_array = np.frombuffer(rom_bytes, dtype=np.uint8)
    env = StellaEnvironment(rom_array)
    # Match xitari's `ALEInterface::resetGame()` boot burn — same as the
    # PXC1 harness.
    env.reset(boot_noop_steps=60, boot_reset_steps=4)

    out: list[bytes] = []
    for a in actions:
        env.step(int(a))
        ram = np.asarray(env.get_ram(), dtype=np.uint8)
        out.append(bytes(int(b) for b in ram))
    return out


# --------------------------------------------------------------------------- #
# Parametric tests — one per ROM. Missing fixtures are skipped per-case.
# --------------------------------------------------------------------------- #

@pytest.mark.parametrize("case", _PXC2_CASES, ids=lambda c: c.name)
def test_jutari_fixture_matches_xitari_trace_frame_count(case: _RomCase):
    """Both fixture traces should cover the same number of frames so
    the cross-check is well-defined."""
    if not _have_fixtures(case):
        pytest.skip(_skip_reason(case))
    xitari_actions = _load_actions(_xitari_trace_path(case))
    jutari_actions = _load_actions(_jutari_trace_path(case))
    assert len(xitari_actions) == len(jutari_actions), (
        f"[{case.name}] xitari and jutari fixtures have different "
        "lengths — regenerate the jutari fixture from the same xitari trace.")


@pytest.mark.parametrize("case", _PXC2_CASES, ids=lambda c: c.name)
def test_jaxtari_matches_jutari_per_frame_ram(case: _RomCase):
    """The headline PXC2 assertion: jaxtari and jutari produce
    byte-identical RAM at every frame of the canonical fixture trace,
    regardless of whether either matches xitari."""
    if not _have_fixtures(case):
        pytest.skip(_skip_reason(case))
    rom_bytes    = _rom_path(case).read_bytes()
    actions      = _load_actions(_xitari_trace_path(case))
    jutari_rams  = _load_ram_per_frame(_jutari_trace_path(case))
    jaxtari_rams = _jaxtari_ram_per_frame(rom_bytes, actions)

    assert len(jutari_rams) == len(jaxtari_rams), (
        f"[{case.name}] frame-count mismatch between jutari fixture "
        "and the live jaxtari run")

    for i, (jax_ram, jul_ram) in enumerate(zip(jaxtari_rams, jutari_rams)):
        if jax_ram != jul_ram:
            diffs = [(addr, jax_ram[addr], jul_ram[addr])
                     for addr in range(len(jax_ram))
                     if jax_ram[addr] != jul_ram[addr]]
            msg = f"[{case.name}] frame {i} divergence ({len(diffs)} bytes):\n"
            for addr, jx, jl in diffs[:16]:
                msg += f"  RAM[${addr:02x}]: jaxtari=${jx:02x}  jutari=${jl:02x}\n"
            pytest.fail(msg)


@pytest.mark.parametrize("case", _PXC2_CASES, ids=lambda c: c.name)
def test_pxc2_jaxtari_vs_xitari_divergence_pattern_unchanged(case: _RomCase):
    """The divergence from xitari is stable too — locks in the
    PXC1-x-documented "same N bytes diverge identically in both
    ports" property. If this fires, either: (a) jaxtari closed some
    of the gap (good — update the jutari fixture too and keep them
    in lock-step), or (b) something else regressed.

    Cases with `expected_xitari_divergence=-1` are exploratory: the
    test skips with a message reporting the observed count so a
    maintainer can record it for the next commit."""
    if not _have_fixtures(case):
        pytest.skip(_skip_reason(case))
    rom_bytes    = _rom_path(case).read_bytes()
    actions      = _load_actions(_xitari_trace_path(case))
    xitari_rams  = _load_ram_per_frame(_xitari_trace_path(case))
    jaxtari_rams = _jaxtari_ram_per_frame(rom_bytes, actions)

    last_xi = xitari_rams[-1]
    last_jx = jaxtari_rams[-1]
    diff_count = sum(1 for a, b in zip(last_xi, last_jx) if a != b)

    if case.expected_xitari_divergence < 0:
        pytest.skip(
            f"[{case.name}] expected-divergence not yet captured; "
            f"observed {diff_count} bytes on the last frame — record "
            f"this value in `_PXC2_CASES` and rerun."
        )

    assert diff_count == case.expected_xitari_divergence, (
        f"[{case.name}] jaxtari-vs-xitari divergence at frame "
        f"{len(xitari_rams) - 1} is now {diff_count} bytes (was "
        f"{case.expected_xitari_divergence}). If this is from a real "
        f"emulation fix, update the case's expected divergence + "
        f"regenerate the jutari fixture in the same commit so both "
        f"ports move in lock-step.")
