"""PXC2 — jaxtari ≡ jutari direct cross-check.

PXC1 / PXC1-x established that the same 10 RAM bytes diverge
identically in jaxtari and jutari when both are checked against the
xitari reference trace. PXC2 makes that *implicit* equality
*explicit*: drive both jaxtari (live) and jutari (a pre-committed
trace dump under `tools/fixtures/traces/`) with the same action
sequence and assert their per-frame RAM is byte-exact identical.

A regression where one port "improves" by closing some of the 10-byte
gap without the other port matching it would fail this test — the
divergence pattern is intentionally locked in until PXC1-x round 3+
closes it on both sides simultaneously.

The jutari fixture is generated by `tools/jutari_trace_dump.jl`. If
you change jutari emulation in a way that legitimately moves the
divergence pattern, re-run that script to refresh the fixture (and
ensure the jaxtari side moves in lock-step in the same commit, per
PXC2's standing rule).
"""

from __future__ import annotations

import json
from pathlib import Path

import numpy as np
import pytest

from jaxtari.env.stella_environment import StellaEnvironment


_REPO_ROOT      = Path(__file__).resolve().parents[2]
_ROM_PATH       = _REPO_ROOT / "xitari" / "roms" / "pong.bin"
_XITARI_TRACE   = _REPO_ROOT / "tools" / "fixtures" / "traces" / "pong_noop_10.jsonl"
_JUTARI_TRACE   = _REPO_ROOT / "tools" / "fixtures" / "traces" / "pong_noop_10_jutari.jsonl"


def _load_actions(trace_path: Path) -> list[int]:
    out: list[int] = []
    with open(trace_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            out.append(int(json.loads(line)["action"]))
    return out


def _load_ram_per_frame(trace_path: Path) -> list[bytes]:
    rams: list[bytes] = []
    with open(trace_path) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            rec = json.loads(line)
            rams.append(bytes.fromhex(rec["ram"]))
    return rams


def _jaxtari_ram_per_frame(rom_bytes: bytes, actions: list[int]) -> list[bytes]:
    rom_array = np.frombuffer(rom_bytes, dtype=np.uint8)
    env = StellaEnvironment(rom_array)
    # Match xitari's `ALEInterface::resetGame()` boot burn — same as the
    # PXC1 harness.
    env.reset(boot_noop_steps=60, boot_reset_steps=4)

    out: list[bytes] = []
    for a in actions:
        env.step(int(a))
        ram = np.asarray(env.get_ram(), dtype=np.uint8)
        out.append(bytes(int(b) for b in ram))
    return out


# --------------------------------------------------------------------------- #
# Fixture presence — skip rather than fail in environments that haven't
# generated the jutari trace yet.
# --------------------------------------------------------------------------- #

_HAVE_FIXTURES = _ROM_PATH.is_file() and _XITARI_TRACE.is_file() and _JUTARI_TRACE.is_file()
_SKIP_REASON   = (
    f"PXC2 fixtures missing — rerun "
    f"`julia --project=jutari tools/jutari_trace_dump.jl --rom {_ROM_PATH} "
    f"--trace {_XITARI_TRACE} --out {_JUTARI_TRACE}` to regenerate."
)


@pytest.mark.skipif(not _HAVE_FIXTURES, reason=_SKIP_REASON)
def test_jutari_fixture_matches_xitari_trace_frame_count():
    """Both fixture traces should cover the same number of frames so
    the cross-check is well-defined."""
    xitari_actions = _load_actions(_XITARI_TRACE)
    jutari_actions = _load_actions(_JUTARI_TRACE)
    assert len(xitari_actions) == len(jutari_actions), (
        "xitari and jutari fixtures have different lengths — regenerate the "
        "jutari fixture from the same xitari trace.")


@pytest.mark.skipif(not _HAVE_FIXTURES, reason=_SKIP_REASON)
def test_jaxtari_matches_jutari_per_frame_ram_on_pong_noop_10():
    """The headline PXC2 assertion: jaxtari and jutari produce
    byte-identical RAM at every frame of the canonical fixture trace,
    regardless of whether either matches xitari."""
    rom_bytes      = _ROM_PATH.read_bytes()
    actions        = _load_actions(_XITARI_TRACE)
    jutari_rams    = _load_ram_per_frame(_JUTARI_TRACE)
    jaxtari_rams   = _jaxtari_ram_per_frame(rom_bytes, actions)

    assert len(jutari_rams) == len(jaxtari_rams), (
        "frame-count mismatch between jutari fixture and the live jaxtari run")

    for i, (jax_ram, jul_ram) in enumerate(zip(jaxtari_rams, jutari_rams)):
        if jax_ram != jul_ram:
            diffs = [(addr, jax_ram[addr], jul_ram[addr])
                     for addr in range(len(jax_ram))
                     if jax_ram[addr] != jul_ram[addr]]
            msg = f"frame {i} divergence ({len(diffs)} bytes):\n"
            for addr, jx, jl in diffs[:16]:
                msg += f"  RAM[${addr:02x}]: jaxtari=${jx:02x}  jutari=${jl:02x}\n"
            pytest.fail(msg)


@pytest.mark.skipif(not _HAVE_FIXTURES, reason=_SKIP_REASON)
def test_pxc2_jaxtari_vs_xitari_divergence_pattern_unchanged():
    """The divergence from xitari is stable too — locks in the
    PXC1-x-documented "same 10 bytes diverge identically in both
    ports" property. If this fires, either: (a) jaxtari closed some
    of the 10-byte gap (good — update the jutari fixture too and
    keep them in lock-step), or (b) something else regressed."""
    rom_bytes    = _ROM_PATH.read_bytes()
    actions      = _load_actions(_XITARI_TRACE)
    xitari_rams  = _load_ram_per_frame(_XITARI_TRACE)
    jaxtari_rams = _jaxtari_ram_per_frame(rom_bytes, actions)

    # On the last frame, count how many bytes differ from xitari.
    last_xi  = xitari_rams[-1]
    last_jx  = jaxtari_rams[-1]
    diff_count = sum(1 for a, b in zip(last_xi, last_jx) if a != b)

    # Per STATUS.md the divergence is exactly 10 bytes after PXC1-x
    # round 1. Lock that in as a regression guard — moves only when
    # closing the gap deliberately (and the deliberate-close commit
    # should update this number).
    assert diff_count == 10, (
        f"jaxtari-vs-xitari divergence at frame {len(xitari_rams) - 1} is "
        f"now {diff_count} bytes (was 10). If this is from a real "
        f"emulation fix, update PXC2's expected divergence + regenerate "
        f"the jutari fixture and confirm both ports moved in lock-step.")
