#!/usr/bin/env python3
"""Generate BOARD.md from the P2 backlog item files (Scrum Master tool).

Run at each Planning/Review from this directory:  python3 build_board.py
The board is SM-only (SCRUM §2); developers never edit it. Per-sprint file-scope
disjointness (SCRUM §0) is enforced at Planning, not here.
"""
import re, glob, os
from collections import Counter

HERE = os.path.dirname(os.path.abspath(__file__))


def parse(path):
    txt = open(path).read()
    m = re.search(r'^---\n(.*?)\n---', txt, re.S)
    if not m:
        return {}
    fm, key = {}, None
    for line in m.group(1).split('\n'):
        if re.match(r'^\s+-\s+', line):
            if not isinstance(fm.get(key), list):
                fm[key] = []
            fm[key].append(re.sub(r'^\s+-\s+', '', line).strip())
        else:
            mm = re.match(r'^([a-z_]+):\s*(.*)$', line)
            if mm:
                key, val = mm.group(1), mm.group(2).strip()
                if val.startswith('[') and val.endswith(']'):
                    val = [x.strip() for x in val[1:-1].split(',') if x.strip()]
                fm[key] = val
    return fm


def sortkey(fm):
    iid = fm.get('id', '')
    m = re.match(r'P2-E(\d+)-(\d+)', iid)
    if m:
        return (0, int(m.group(1)), int(m.group(2)), '')
    # Revision items (P2-R-*) sort after all epic items, alphabetically by id.
    if iid.startswith('P2-R-'):
        return (1, 0, 0, iid)
    return (2, 99, 99, iid)


def as_list(v):
    return ', '.join(v) if isinstance(v, list) else (v or '')


def as_scope(v):
    items = v if isinstance(v, list) else ([v] if v else [])
    return '<br>'.join('`%s`' % x for x in items)


items = sorted((p for p in (parse(f) for f in glob.glob(os.path.join(HERE, 'P2-*.md'))) if p.get('id')),
               key=sortkey)

out = ['# P2 sprint board', '',
       '> Auto-generated by `build_board.py` from the `P2-*.md` frontmatter. '
       '**%d items.** SM-only (SCRUM §2); regenerate at each Planning/Review. '
       'Per-sprint file-scope disjointness is enforced at Planning (SCRUM §0).' % len(items),
       '',
       '| ID | Title | Epic | Sprint | Owner | Where | Status | Depends on | File-scope |',
       '|----|-------|------|--------|-------|-------|--------|------------|------------|']
for i in items:
    out.append('| %s | %s | %s | %s | %s | %s | %s | %s | %s |' % (
        i.get('id', ''), i.get('title', '').replace('|', '/'), i.get('epic', '').split(' ')[0],
        i.get('sprint', '') or '', i.get('owner', '') or '—', i.get('where', ''),
        i.get('status', ''), as_list(i.get('depends_on', '')), as_scope(i.get('file_scope', ''))))

c = Counter(str(i.get('sprint', '?') or '?') for i in items)
out += ['', '## Items per sprint', ', '.join('Sprint %s: %d' % (k, c[k]) for k in sorted(c)),
        '', '## Sprint log', 'See [`../sprints/`](../sprints/) for per-sprint Planning + Review notes.']

open(os.path.join(HERE, 'BOARD.md'), 'w').write('\n'.join(out) + '\n')
print('wrote BOARD.md with %d items' % len(items))
