"""
    CPUTables

6502 opcode lookup tables. Two parallel 256-entry arrays indexed by opcode
(use `tbl[opcode + 1]` for 1-based access):

- `ADDRESSING_MODE_TABLE` → one of the `ADDR_*` constants.
- `CYCLE_TABLE`           → base cycle count for the opcode (no page-cross
  or branch-taken penalty; those are added at runtime in `CPU.step`).

Both tables match the standard NMOS 6502 set. Undocumented opcodes have
plausible cycle counts but no implementation in P1 (see PORTING_PLAN.md §5 P1f).
"""
module CPUTables

export ADDRESSING_MODE_TABLE, CYCLE_TABLE,
       ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_ZERO, ADDR_ZERO_X, ADDR_ZERO_Y,
       ADDR_ABSOLUTE, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_Y,
       ADDR_INDIRECT, ADDR_INDIRECT_X, ADDR_INDIRECT_Y, ADDR_RELATIVE,
       FLAG_N, FLAG_V, FLAG_U, FLAG_B, FLAG_D, FLAG_I, FLAG_Z, FLAG_C

const ADDR_IMPLIED      = UInt8(0)
const ADDR_IMMEDIATE    = UInt8(1)
const ADDR_ZERO         = UInt8(2)
const ADDR_ZERO_X       = UInt8(3)
const ADDR_ZERO_Y       = UInt8(4)
const ADDR_ABSOLUTE     = UInt8(5)
const ADDR_ABSOLUTE_X   = UInt8(6)
const ADDR_ABSOLUTE_Y   = UInt8(7)
const ADDR_INDIRECT     = UInt8(8)
const ADDR_INDIRECT_X   = UInt8(9)
const ADDR_INDIRECT_Y   = UInt8(10)
const ADDR_RELATIVE     = UInt8(11)

const ADDRESSING_MODE_TABLE = UInt8[
    # 0x0?
    ADDR_IMPLIED, ADDR_INDIRECT_X, ADDR_IMPLIED, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0x1?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X,
    # 0x2?
    ADDR_ABSOLUTE, ADDR_INDIRECT_X, ADDR_IMPLIED, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0x3?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X,
    # 0x4?
    ADDR_IMPLIED, ADDR_INDIRECT_X, ADDR_IMPLIED, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0x5?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X,
    # 0x6?
    ADDR_IMPLIED, ADDR_INDIRECT_X, ADDR_IMPLIED, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_INDIRECT, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0x7?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X,
    # 0x8?
    ADDR_IMMEDIATE, ADDR_INDIRECT_X, ADDR_IMMEDIATE, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0x9?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_Y, ADDR_ZERO_Y,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_Y, ADDR_ABSOLUTE_Y,
    # 0xA?
    ADDR_IMMEDIATE, ADDR_INDIRECT_X, ADDR_IMMEDIATE, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0xB?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_Y, ADDR_ZERO_Y,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_Y, ADDR_ABSOLUTE_Y,
    # 0xC?
    ADDR_IMMEDIATE, ADDR_INDIRECT_X, ADDR_IMMEDIATE, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0xD?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X,
    # 0xE?
    ADDR_IMMEDIATE, ADDR_INDIRECT_X, ADDR_IMMEDIATE, ADDR_INDIRECT_X,
    ADDR_ZERO, ADDR_ZERO, ADDR_ZERO, ADDR_ZERO,
    ADDR_IMPLIED, ADDR_IMMEDIATE, ADDR_IMPLIED, ADDR_IMMEDIATE,
    ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE, ADDR_ABSOLUTE,
    # 0xF?
    ADDR_RELATIVE, ADDR_INDIRECT_Y, ADDR_IMPLIED, ADDR_INDIRECT_Y,
    ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X, ADDR_ZERO_X,
    ADDR_IMPLIED, ADDR_ABSOLUTE_Y, ADDR_IMPLIED, ADDR_ABSOLUTE_Y,
    ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X, ADDR_ABSOLUTE_X,
]

const CYCLE_TABLE = UInt8[
    7, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 4, 4, 6, 6,  # 0
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,  # 1
    6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 4, 4, 6, 6,  # 2
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,  # 3
    6, 6, 2, 8, 3, 3, 5, 5, 3, 2, 2, 2, 3, 4, 6, 6,  # 4
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,  # 5
    6, 6, 2, 8, 3, 3, 5, 5, 4, 2, 2, 2, 5, 4, 6, 6,  # 6
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,  # 7
    2, 6, 2, 6, 3, 3, 3, 3, 2, 2, 2, 2, 4, 4, 4, 4,  # 8
    2, 6, 2, 6, 4, 4, 4, 4, 2, 5, 2, 5, 5, 5, 5, 5,  # 9
    2, 6, 2, 6, 3, 3, 3, 4, 2, 2, 2, 2, 4, 4, 4, 4,  # A
    2, 5, 2, 5, 4, 4, 4, 4, 2, 4, 2, 4, 4, 4, 4, 4,  # B
    2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6,  # C
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,  # D
    2, 6, 2, 8, 3, 3, 5, 5, 2, 2, 2, 2, 4, 4, 6, 6,  # E
    2, 5, 2, 8, 4, 4, 6, 6, 2, 4, 2, 7, 4, 4, 7, 7,  # F
]

# 6502 status register bit masks
const FLAG_N = UInt8(0x80)
const FLAG_V = UInt8(0x40)
const FLAG_U = UInt8(0x20)
const FLAG_B = UInt8(0x10)
const FLAG_D = UInt8(0x08)
const FLAG_I = UInt8(0x04)
const FLAG_Z = UInt8(0x02)
const FLAG_C = UInt8(0x01)

end # module
