#!/usr/bin/env python3
"""Render the results-audit site from manifest.py into docs/*.html.

Pure standard library. Run from anywhere:  python3 docs/build_pages.py
Re-run after editing manifest.py or regenerating assets.
"""
import html
import os
import subprocess
import sys

import json as _json

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import manifest as M  # noqa: E402


# ---------------------------------------------------------------------------
# The SINGLE source of Paper-2 result numbers. Generated by docs/gen_site_data.py
# from the committed analysis outputs; every P2 faithfulness number rendered on
# the site is looked up here, so no two pages can show a conflicting value.
# Run `python3 docs/gen_site_data.py` before this script.
# ---------------------------------------------------------------------------
SITE = _json.load(open(os.path.join(HERE, "site_data.json")))


GAME_NAMES = {
    "ms_pacman": "Ms. Pac-Man", "qbert": "Q*bert", "up_n_down": "Up'n Down",
    "space_invaders": "Space Invaders", "beam_rider": "Beam Rider",
    "video_pinball": "Video Pinball", "private_eye": "Private Eye",
    "montezuma_revenge": "Montezuma's Revenge", "yars_revenge": "Yars' Revenge",
    "kung_fu_master": "Kung-Fu Master", "road_runner": "Road Runner",
    "star_gunner": "Star Gunner", "double_dunk": "Double Dunk",
    "battle_zone": "Battle Zone", "crazy_climber": "Crazy Climber",
    "chopper_command": "Chopper Command", "demon_attack": "Demon Attack",
    "air_raid": "Air Raid", "bank_heist": "Bank Heist", "fishing_derby": "Fishing Derby",
    "ice_hockey": "Ice Hockey", "name_this_game": "Name This Game",
    "time_pilot": "Time Pilot",
}


def game_disp(g):
    return GAME_NAMES.get(g, g.replace("_", " ").title())


def _num(x, dashes="n/a"):
    """Render a store number to 3 decimals, or a placeholder when null."""
    if x is None:
        return dashes
    if isinstance(x, (int, float)):
        return "%.3f" % x
    return str(x)


def p2_headline_fields():
    """The flat {placeholder: value} map used to fill P2 prose templates
    (blurb, E6 claim). Every value comes from SITE['headline'] / SITE['meta']."""
    h = SITE["headline"]
    m = SITE["meta"]
    return {
        "all_regime_gap": _num(h["all_regime_gap"]),
        "position_gap": _num(h["position_gap"]),
        "position_ci_lo": _num(h["position_ci"][0]),
        "position_ci_hi": _num(h["position_ci"][1]),
        "all_regime_ci_lo": _num(h["all_regime_ci"][0]),
        "all_regime_ci_hi": _num(h["all_regime_ci"][1]),
        "causal_all": _num(h["causal_all"]),
        "grad_all": _num(h["grad_all"]),
        "causal_pos": _num(h["causal_pos"]),
        "grad_pos": _num(h["grad_pos"]),
        "causal_all_n": h["causal_all_n"],
        "grad_all_n": h["grad_all_n"],
        "causal_pos_n": h["causal_pos_n"],
        "grad_pos_n": h["grad_pos_n"],
        "n_methods": m["n_methods"],
        "n_records": m["n_records"],
        "scored_games": m["scored_games"],
    }


def git_head():
    try:
        return subprocess.check_output(
            ["git", "rev-parse", "HEAD"], cwd=REPO).decode().strip()
    except Exception:
        return "main"


HEAD = git_head()
SHORT = HEAD[:8]
BLOB = M.REPO_URL + "/blob/main/"   # links track main so they survive file moves


def src(path, label=None):
    """A link to a source file in the GitHub repo."""
    if not path or path == "—":
        return html.escape(label or "—")
    label = label or path
    return '<a href="%s%s"><code>%s</code></a>' % (BLOB, path, html.escape(label))


def esc(s):
    return html.escape(str(s))


def srcln(path, line, label=None):
    """A GitHub blob link to a specific line of a source file (verified line no)."""
    label = label or ("%s:%d" % (path.rsplit("/", 1)[-1], line))
    return '<a href="%s%s#L%d"><code>%s</code></a>' % (BLOB, path, line, esc(label))


def link(href, label):
    """A link that is external (http), an internal page/anchor, or a repo path."""
    if href.startswith("http") or href.endswith(".html") or href.startswith("#") \
            or ".html#" in href:
        return '<a href="%s">%s</a>' % (href, label)
    return src(href, label)


PAGES = [
    ("index.html", "Overview"),
    ("paper1.html", "Paper 1"),
    ("conformance.html", "Conformance"),
    ("paper2.html", "Paper 2"),
    ("methods.html", "P2 Methods"),
    ("ground_truth.html", "Ground Truth ROMs"),
    ("provenance.html", "Provenance"),
    ("environment.html", "Environment"),
    ("reproduce.html", "Reproduce"),
]


def nav(active):
    items = ['<span class="brand">UnderstandingVCS · results audit</span>']
    for href, label in PAGES:
        cls = ' class="active"' if href == active else ""
        items.append('<a href="%s"%s>%s</a>' % (href, cls, esc(label)))
    return '<nav><div class="wrap">%s</div></nav>' % "".join(items)


def page(active, title, body):
    return """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>%s</title>
<meta name="description" content="Reproducibility and provenance audit for the UnderstandingVCS papers.">
<link rel="stylesheet" href="assets/css/style.css">
</head>
<body>
%s
%s
<footer><div class="wrap">
Built from <a href="%s/commit/%s"><code>%s</code></a> ·
source of truth: <code>docs/manifest.py</code> ·
regenerate with <code>python3 docs/build_assets.py &amp;&amp; python3 docs/build_pages.py</code> ·
<a href="%s">repository</a>
</div></footer>
</body>
</html>
""" % (esc(title), nav(active), body, M.REPO_URL, HEAD, SHORT, M.REPO_URL)


def render_ledger(claims):
    rows = []
    for c in claims:
        st = c["status"]
        meta_rows = [
            ("Script", src(c["script"])),
            ("Command", '<code class="cmd">%s</code>' % esc(c["command"])),
            ("Artifact", src(c["artifact"])),
        ]
        # optional: the upstream scripts that produce this row's input data
        if c.get("inputs"):
            items = "".join(
                "<li>%s — %s</li>" % (src(p), desc) for p, desc in c["inputs"])
            meta_rows.append(("Input data", '<ul class="inputs">%s</ul>' % items))
        meta_rows += [
            ("Runtime", esc(c["runtime"])),
            ("Hardware", esc(c["hardware"])),
            ("Verified by", c["verified_by"]),  # may contain inline html/code refs
        ]
        meta = "".join("<dt>%s</dt><dd>%s</dd>" % (k, v) for k, v in meta_rows)
        # optional: a short "where this comes from" comment under the meta
        note = '<p class="rownote">%s</p>' % c["note"] if c.get("note") else ""
        rows.append("""
<div class="row">
  <div class="head">
    <span class="claim">%s</span>
    <span class="value">%s</span>
    <span class="badge %s">%s</span>
  </div>
  <div class="body">
    <p class="detail">%s</p>
    <dl class="meta">%s</dl>
    %s
  </div>
</div>""" % (esc(c["claim"]), esc(c["value"]), st, st, c["detail"], meta, note))
    return '<div class="ledger">%s</div>' % "".join(rows)


def render_figures(figs):
    cells = []
    for base, title, desc in figs:
        cells.append("""
<div class="fig">
  <a href="assets/img/%s.png" target="_blank"><img src="assets/img/%s.png" alt="%s"></a>
  <h4>%s</h4><p>%s</p>
</div>""" % (base, base, esc(title), esc(title), esc(desc)))
    return '<div class="figrid">%s</div>' % "".join(cells)


def render_videos(vids):
    cells = []
    for base, title, desc in vids:
        cells.append("""
<div class="vid">
  <video controls preload="metadata" playsinline>
    <source src="assets/video/%s.mp4" type="video/mp4">
  </video>
  <h4>%s</h4><p>%s</p>
</div>""" % (base, esc(title), esc(desc)))
    return '<div class="vidgrid">%s</div>' % "".join(cells)


# ---------------------------------------------------------------------------
def build_index():
    o = M.ORACLE
    pillars = "".join(
        '<div class="pillar"><b>%s</b><small>%s — %s</small></div>'
        % (esc(t), d, link(href, lbl)) for t, d, lbl, href in o["pillars"])
    cards = ""
    for P in (M.PAPER1, M.PAPER2):
        cards += """
<a class="card" href="%s.html" style="text-decoration:none;color:inherit">
  <span class="venue">%s</span>
  <h3>%s</h3>
  <p>%s</p>
  <p style="color:var(--accent)">Open the evidence ledger →</p>
</a>""" % (P["id"], esc(P["venue"]), esc(P["title"]), esc(P["subtitle"]))

    body = """
<header class="hero"><div class="wrap">
  <h1>Audit every result, down to the script that made it</h1>
  <p class="lead">A reproducibility and provenance dashboard for the two papers built on the
  differentiable Atari&nbsp;2600 VCS. Every claim links to the exact code, command, artifact,
  runtime and hardware — and to the external reference that proves the emulator is real.</p>
  <div class="media">
    <img src="assets/gif/si_compare.gif" alt="Space Invaders: xitari vs jutari vs pixel difference">
    <p class="caption">Space Invaders — <b>xitari</b> (reference C++) · <b>jutari</b> (our Julia port) ·
    <b>pixel difference</b>. The difference panel is solid black: byte-for-byte identical output.</p>
  </div>
</div></header>

<section><div class="wrap">
  <h2>Why you can trust this</h2>
  <p class="sub">%s</p>
  <p>%s</p>
  <div class="pillars">%s</div>
</div></section>

<section><div class="wrap">
  <h2>The two papers</h2>
  <p class="sub">This site covers Paper&nbsp;1 and Paper&nbsp;2 only.</p>
  <div class="cards">%s</div>
</div></section>

<section><div class="wrap">
  <h2>How to read a claim</h2>
  <p class="sub">Each row in a paper’s ledger is one auditable result.</p>
  <table class="tbl">
    <tr><th>Field</th><th>What it gives the reviewer</th></tr>
    <tr><td>Value</td><td>the measured number, read from the committed result file</td></tr>
    <tr><td>Script</td><td>link to the exact source that produces it</td></tr>
    <tr><td>Command</td><td>the verbatim invocation to reproduce it</td></tr>
    <tr><td>Artifact</td><td>the committed output (results table / JSON / figure) it wrote</td></tr>
    <tr><td>Runtime &amp; Hardware</td><td>wall-clock and the machine it ran on</td></tr>
    <tr><td>Verified by</td><td>the test / oracle gate that guards it</td></tr>
    <tr><td>Status</td><td><span class="badge measured">measured</span> vs
      <span class="badge deferred">deferred</span> — we never dress a plan up as a result</td></tr>
  </table>
</div></section>
""" % (esc(o["headline"]), o["body"], pillars, cards)
    return page("index.html", "UnderstandingVCS — results audit", body)


def build_paper(P):
    extra = ""
    blurb = P["blurb"]
    if P["id"] == "paper2":
        f = p2_headline_fields()
        # every number below comes from docs/site_data.json (via f) — none hardcoded
        blurb = blurb.format(**f)
        extra = """
<section><div class="wrap">
  <h2>Headline finding</h2>
  <p class="sub">Aggregated over the <b>{scored_games} scored games</b>, causal/intervention methods
  stay well above gradient and correlational methods — a robust faithfulness gap across all regimes.
  On the discrete sprite-position outputs the naive gradient is exactly zero; the emulator's bilinear
  sampler restores a non-zero position gradient, but its faithfulness stays low, so gradient and
  correlational methods still collapse there. Bootstrapped over the {scored_games} games, the
  position-regime gap is now <b>significant</b> — its 95% confidence interval excludes zero (it
  crossed zero at the original six games).</p>
  <div class="bignum">
    <div class="b"><strong>{all_regime_gap}</strong><small>all-regime faithfulness gap ({scored_games} scored games)</small></div>
    <div class="b"><strong>{causal_all}</strong><small>causal / intervention mean (all regimes, n={causal_all_n})</small></div>
    <div class="b"><strong>{grad_all}</strong><small>gradient / correlational mean (all regimes, n={grad_all_n})</small></div>
    <div class="b"><strong>{n_methods}</strong><small>methods on the leaderboard</small></div>
    <div class="b"><strong>{n_records}</strong><small>per-game records aggregated</small></div>
  </div>
  <p class="caption">Primary contrast from
  <a href="BLOBtools/xai_study/compare/out/leaderboard.json"><code>leaderboard.json</code></a>,
  surfaced through <a href="BLOBdocs/site_data.json"><code>site_data.json</code></a>
  · <code>headline_contrast.all_regimes</code> ({scored_games} scored games).</p>
  <p class="sub" style="margin-top:18px">Position-regime gap — now <b>significant at n&asymp;{scored_games}</b>
  (bootstrap over games, 95% CI excludes zero):</p>
  <div class="bignum">
    <div class="b"><strong>{position_gap}</strong><small>position-regime gap · bootstrap CI [{position_ci_lo}, {position_ci_hi}] (excludes 0)</small></div>
    <div class="b"><strong>{causal_pos}</strong><small>causal / intervention mean (position, n={causal_pos_n})</small></div>
    <div class="b"><strong>{grad_pos}</strong><small>gradient / correlational mean (position, n={grad_pos_n})</small></div>
  </div>
  <p class="caption"><code>headline_contrast.position_regime</code> family means; significance from
  the game-level bootstrap in <code>position_bootstrap.json</code> (n={scored_games} games, 20&#8239;000 resamples).
  The testbed was redesigned to score every method on shared random-action gameplay states — see the
  <a href="BLOBxai_paper/xai_2_interpretability/experiment_redesign.md">experiment redesign note</a>.</p>
</div></section>""".format(**f).replace("BLOB", BLOB)

    links = '<a href="%s%s">paper PDF</a>' % (BLOB, P["pdf"])
    if P.get("supplement_pdf"):
        links += ' · <a href="%s%s">supplement PDF</a>' % (BLOB, P["supplement_pdf"])
    tour = {"paper1": ('conformance.html', "Conformance code tour"),
            "paper2": ('methods.html', "Method catalogue &amp; execution stack")}.get(P["id"])
    if tour:
        links += ' · <a href="%s"><b>%s →</b></a>' % tour

    vids = ""
    if P["videos"]:
        vids = """
<section><div class="wrap">
  <h2>Videos</h2>
  <p class="sub">The supplement divergence clip and the narrated overview.</p>
  %s
</div></section>""" % render_videos(P["videos"])

    gallery = ""
    if P.get("gallery"):
        cells = []
        for game, title in P["gallery"]:
            cells.append("""
<div class="vid">
  <video controls preload="none" playsinline poster="assets/img/poster_%s.jpg">
    <source src="assets/video/cmp_%s.mp4" type="video/mp4">
  </video>
  <h4>%s</h4>
</div>""" % (game, game, esc(title)))
        gallery = """
<section><div class="wrap">
  <h2>Conformance gallery</h2>
  <p class="sub">Each clip is three panels — <b>xitari</b> (reference C++) ·
  <b>jutari</b> (our port) · <b>per-pixel difference</b>. The difference panel stays black
  for the whole clip (only the “DIFFERENCE” header label is lit): byte-for-byte identical
  output. Verified across the full length of all 64 games; a representative selection follows.</p>
  <div class="vidgrid">%s</div>
  <p class="caption">All 64 games render pixel-exact — see the
  <a href="%stools/rom_sweep/results_jutari_screen.md">screen sweep</a>.</p>
</div></section>""" % ("".join(cells), BLOB)

    body = """
<header class="hero"><div class="wrap">
  <span class="venue" style="color:var(--accent-2);font-weight:600">%s</span>
  <h1>%s</h1>
  <p class="lead">%s</p>
  <p style="margin-top:14px">%s · %s</p>
</div></header>

%s

<section><div class="wrap">
  <h2>Evidence ledger</h2>
  <p class="sub">Every claim → script → command → artifact → runtime → hardware → verifying gate.</p>
  %s
</div></section>

<section><div class="wrap">
  <h2>Figures</h2>
  <p class="sub">Rasterised from the paper’s committed PDFs; click to enlarge.</p>
  %s
</div></section>

%s
%s
""" % (esc(P["venue"]), esc(P["title"]), blurb, links, esc(P["subtitle"]),
       extra, render_ledger(_p2_format_claims(P)), render_figures(P["figures"]), gallery, vids)
    return page(P["id"] + ".html", P["title"], body)


def _p2_format_claims(P):
    """Fill any {placeholder} in a paper's claim `value`/`detail` from the store.
    Non-P2 papers and claims without placeholders pass through unchanged."""
    if P["id"] != "paper2":
        return P["claims"]
    f = p2_headline_fields()
    out = []
    for c in P["claims"]:
        c2 = dict(c)
        for k in ("value", "detail"):
            if isinstance(c2.get(k), str) and "{" in c2[k]:
                c2[k] = c2[k].format(**f)
        out.append(c2)
    return out


def build_provenance():
    PR = M.PROVENANCE
    def lst(items, three=False):
        out = []
        for it in items:
            if three:
                a, b, p = it
                out.append("<tr><td><b>%s</b></td><td>%s</td><td>%s</td></tr>"
                           % (esc(a), b, src(p)))
            else:
                a, b = it
                out.append("<tr><td><b>%s</b></td><td>%s</td></tr>" % (esc(a), b))
        return "".join(out)

    tests = "".join("<tr><td><b>%s</b></td><td>%s</td><td>%s</td></tr>"
                    % (esc(a), b, src(p)) for a, b, p in PR["tests"])
    repro = "".join("<p><b>%s</b></p><pre><code>%s</code></pre>" % (esc(a), esc(b))
                    for a, b in PR["reproduce"])

    body = """
<header class="hero"><div class="wrap">
  <h1>Provenance &amp; reproducibility</h1>
  <p class="lead">The infrastructure a skeptical reviewer can use to confirm the code and
  experiments are real: an external oracle, conformance harnesses, a large test suite,
  continuous integration, and an open development log.</p>
</div></header>

<section><div class="wrap">
  <h2>The external oracle</h2>
  <p>%s The reference emulator lives at %s with its determinism patch at %s.</p>
</div></section>

<section><div class="wrap">
  <h2>Conformance harnesses</h2>
  <p class="sub">For a line-by-line walk of each harness's call stack, see the
  <a href="conformance.html">conformance code tour</a>.</p>
  <table class="tbl"><tr><th>Harness</th><th>What it asserts</th><th>Source</th></tr>%s</table>
</div></section>

<section><div class="wrap">
  <h2>Comparison tooling</h2>
  <table class="tbl"><tr><th>Tool</th><th>Purpose</th><th>Source</th></tr>%s</table>
</div></section>

<section><div class="wrap">
  <h2>Test suite</h2>
  <table class="tbl"><tr><th>Port</th><th>Count</th><th>Location</th></tr>%s</table>
  <div class="note">%s</div>
</div></section>

<section><div class="wrap">
  <h2>Continuous integration</h2>
  <table class="tbl"><tr><th>Workflow</th><th>Runs</th><th>Source</th></tr>%s</table>
</div></section>

<section><div class="wrap">
  <h2>Development log</h2>
  <table class="tbl"><tr><th>Document</th><th>Role</th><th>Source</th></tr>%s</table>
</div></section>

<section><div class="wrap">
  <h2>Reproduce the conformance numbers</h2>
  %s
</div></section>
""" % (M.ORACLE["body"], src("xitari/"), src("tools/xitari_conformance_seed.patch"),
       lst(PR["harnesses"], three=True), lst(PR["tools"], three=True), tests,
       PR["tests_note"], lst(PR["ci"], three=True), lst(PR["logs"], three=True), repro)
    return page("provenance.html", "Provenance", body)


def build_environment():
    E = M.ENVIRONMENT
    hw = "".join("<tr><td><b>%s</b></td><td>%s</td><td>%s</td></tr>"
                 % (esc(a), esc(b), esc(c)) for a, b, c in E["hardware"])
    sw = "".join("<tr><td><b>%s</b></td><td>%s</td><td>%s</td></tr>"
                 % (esc(a), esc(b), esc(c)) for a, b, c in E["software"])
    det = "".join("<li>%s</li>" % d for d in E["determinism"])
    roms = "".join("<tr><td><code>%s</code></td><td>%s</td><td><code>%s</code></td></tr>"
                   % (esc(g), esc(s), esc(h)) for g, s, h in E["roms"]["rows"])

    body = """
<header class="hero"><div class="wrap">
  <h1>Environment &amp; hardware</h1>
  <p class="lead">Where every number was produced: machines, pinned software, seeds and
  byte-verified inputs.</p>
</div></header>

<section><div class="wrap">
  <h2>Hardware</h2>
  <table class="tbl"><tr><th>Role</th><th>Machine</th><th>Used for</th></tr>%s</table>
</div></section>

<section><div class="wrap">
  <h2>Software (pinned)</h2>
  <table class="tbl"><tr><th>Component</th><th>Version</th><th>Pin</th></tr>%s</table>
</div></section>

<section><div class="wrap">
  <h2>Determinism &amp; seeds</h2>
  <ul>%s</ul>
</div></section>

<section><div class="wrap">
  <h2>ROM provenance</h2>
  <p class="sub">%s</p>
  <table class="tbl"><tr><th>Game</th><th>Size</th><th>SHA-256 (prefix)</th></tr>%s</table>
  <p class="caption">Full table: %s · verify with
  <code>python3 tools/xai_study/repro/make_hash_tables.py --verify</code>.</p>
</div></section>
""" % (hw, sw, det, esc(E["roms"]["note"]), roms, src(E["roms"]["table"]))
    return page("environment.html", "Environment", body)


def build_reproduce():
    PR = M.PROVENANCE
    repro = "".join("<p><b>%s</b></p><pre><code>%s</code></pre>" % (esc(a), esc(b))
                    for a, b in PR["reproduce"])
    # gather every command from both papers
    rows = []
    for P in (M.PAPER1, M.PAPER2):
        for c in P["claims"]:
            if c["command"] and c["command"] != "—":
                rows.append("<tr><td>%s</td><td><code class=\"cmd\">%s</code></td><td>%s</td></tr>"
                            % (esc(c["claim"]), esc(c["command"]), src(c["artifact"])))
    table = "".join(rows)

    body = """
<header class="hero"><div class="wrap">
  <h1>Reproduce</h1>
  <p class="lead">Clone the repo, run the gates, then regenerate any single number from the
  command in its ledger row. ROMs come from AutoROM and are SHA-256 verified.</p>
</div></header>

<section><div class="wrap">
  <h2>Conformance gates</h2>
  %s
</div></section>

<section><div class="wrap">
  <h2>Per-claim commands</h2>
  <p class="sub">The exact invocation behind every ledger row, and the artifact it writes.</p>
  <table class="tbl"><tr><th>Claim</th><th>Command</th><th>Artifact</th></tr>%s</table>
</div></section>

<section><div class="wrap">
  <h2>Rebuild this site</h2>
  <pre><code>python3 docs/build_assets.py   # PDFs/MP4s -> web img/gif/mp4
python3 docs/build_pages.py    # manifest.py -> docs/*.html</code></pre>
</div></section>
""" % (repro, table)
    return page("reproduce.html", "Reproduce", body)


def _stack(rows):
    """rows: list of (step_html, computes_html) -> a 2-col call-stack table."""
    body = "".join("<tr><td>%s</td><td>%s</td></tr>" % (s, c) for s, c in rows)
    return ('<table class="tbl"><tr><th>Step in the call stack</th>'
            '<th>What is actually computed</th></tr>%s</table>' % body)


def build_conformance():
    # Every link below points at a line number verified against the source.
    T_PXC1 = "jaxtari/tests/test_pxc1_conformance.py"
    CHK = "tools/check_trace.py"
    CHKJL = "tools/check_trace.jl"
    ENV = "jaxtari/jaxtari/env/stella_environment.py"
    CON = "jaxtari/jaxtari/console.py"
    CPU = "jaxtari/jaxtari/cpu/m6502.py"
    T_PXC2 = "jaxtari/tests/test_pxc2_jaxtari_vs_jutari.py"
    T_SCR = "jaxtari/tests/test_screen_conformance.py"
    T_K = "jaxtari/tests/test_pxc4_klaus_dormann.py"
    TD = "tools/trace_dump.cpp"
    JDUMP = "tools/jutari_trace_dump.jl"

    intro = """
<header class="hero"><div class="wrap">
  <h1>Conformance harness — a guided code tour</h1>
  <p class="lead">A reviewer should be able to confirm what every conformance test computes
  without reading the whole codebase. This page walks the function stack of each harness —
  from the test assertion, through the replay driver, down into the emulator core where the
  compared bytes are produced — with a line-anchored link at every step. The documentation in
  the code explains <i>how</i> each function works; this page explains <i>what is being
  checked and why it is evidence</i>.</p>
  <p style="margin-top:12px"><a href="#oracle">The oracle pipeline</a> ·
  <a href="#pxc1">PXC1 (RAM/CPU)</a> · <a href="#pxc2">PXC2 (dual-port)</a> ·
  <a href="#pxcs">PXC-S (screen)</a> · <a href="#pxc4">PXC4 (6502)</a> ·
  <a href="#core">the emulator core</a></p>
</div></header>"""

    oracle = """
<section id="oracle"><div class="wrap">
  <h2>How conformance is established</h2>
  <p>Every test compares one of our ports against <b>xitari</b>, the external
  C&plus;&plus; reference emulator (<a href="https://github.com/google-deepmind/xitari">google-deepmind/xitari</a>).
  The comparison runs in two stages. First, xitari is driven by a fixed action stream and its
  per-frame state is dumped to a JSONL trace. Then a port is driven by the <i>same</i> action
  stream and its state is diffed against that trace, frame by frame.</p>
  <pre><code>  fixed action stream
        │
        ▼
  %s  ──▶  JSONL trace (per frame: ram, optional cpu / screen)
   (drives the real xitari C++ emulator: ale.act, ale.getRAM, ale.getScreen)
        │                                         committed under tools/fixtures/
        ▼
  %s  ──▶  steps a port with the same actions, diffs each frame
        │
        ▼
  PXC1 (RAM+CPU)   PXC2 (port≡port)   PXC-S (screen)   PXC4 (6502 ISA)</code></pre>
  <p>The JSONL record for one frame holds the absolute frame index, the action applied, the
  128 B of RIOT RAM as 256 hex chars, and — when the relevant flag is set — the six CPU
  registers and the 210&times;160 framebuffer. The RAM bytes are read out of xitari at
  %s and hex-encoded at %s; the CPU registers are tapped through a
  <code>friend class CpuDebug</code> at %s so xitari's headers are never modified.</p>
</div></section>""" % (
        srcln(TD, 132, "trace_dump.cpp · main"),
        srcln(CHK, 123, "check_trace.py · check_trace"),
        srcln(TD, 256, "trace_dump.cpp:256 · ale.getRAM()"),
        srcln(TD, 67, "trace_dump.cpp:67 · hex_encode"),
        srcln(TD, 54, "trace_dump.cpp:54 · CpuDebug"),
    )

    pxc1 = """
<section id="pxc1"><div class="wrap">
  <h2>PXC1 — RAM &amp; CPU trace replay</h2>
  <p class="sub">Does a port reproduce xitari's RAM (and CPU registers) frame-for-frame?</p>
  <p>The test loads an xitari trace, replays the same actions through the port, and asserts the
  port's 128 B RIOT RAM hex-matches the trace at every frame. A mismatch raises at the first
  diverging frame with a byte-level diff.</p>
  %s
  <p><b>How to read it.</b> The assertion that matters is the hex-string compare at
  %s: the port's RAM is read at %s, hex-encoded, and compared to the trace's
  <code>ram</code> field. If they differ the harness reports the frame and the differing byte
  addresses, then raises. The Julia port is checked by the mirror harness %s.</p>
</div></section>""" % (
        _stack([
            (srcln(T_PXC1, 61, "test_pxc1_conformance.py:61 · test_jaxtari_matches_xitari…"),
             "Entry point. Builds the port from the ROM, replays the trace, asserts all 10 "
             "frames matched (%s)." % srcln(T_PXC1, 80, "L80 · assert matched == 10")),
            (srcln(CHK, 123, "check_trace.py:123 · check_trace(rom, trace)"),
             "Constructs the environment, boots it the same way xitari boots (60 NOOP + 4 RESET), "
             "then loops the trace's actions."),
            (srcln(CHK, 175, "check_trace.py:175 · ram_hex != ref['ram']"),
             "<b>The core check.</b> Per frame: encode the port RAM, compare to the reference hex; "
             "on mismatch emit a byte diff and raise <code>ConformanceError</code>."),
            (srcln(ENV, 375, "stella_environment.py:375 · step(action)"),
             "Applies the action and runs one frame to the next VSYNC — the port advance."),
            (srcln(ENV, 492, "stella_environment.py:492 · get_ram()"),
             "Returns the 128 B RIOT RAM (<code>console.bus.ram</code>) — the exact bytes compared."),
        ]),
        srcln(CHK, 175, "check_trace.py:175"),
        srcln(ENV, 492, "get_ram()"),
        srcln(CHKJL, 61, "check_trace.jl:61 · check_trace"),
    )

    pxc2 = """
<section id="pxc2"><div class="wrap">
  <h2>PXC2 — dual-port cross-check</h2>
  <p class="sub">Do the JAX port and the Julia port diverge from xitari <i>identically</i>?</p>
  <p>This is the claim featured on the front page. Two independently written ports — one in
  JAX, one in Julia — are required to produce <b>byte-identical RIOT RAM at every frame</b>.
  Where they still differ from xitari, they must differ in the <i>same</i> bytes by the
  <i>same</i> amount. Two separate implementations agreeing to the bit is strong evidence of a
  shared, correct mechanism rather than two coincidental bugs.</p>
  %s
  <p><b>How to read it.</b> The headline test runs jaxtari <i>live</i> and loads the jutari
  result from a committed fixture trace (produced by %s). The compare at
  %s is a plain byte-equality of the two ports' RAM per frame; on any mismatch it
  fails at %s with the frame index and differing addresses. A third test
  (%s) locks in the residual divergence-from-xitari count per ROM, so a real
  emulation fix must move <i>both</i> ports in the same commit — they can never drift apart
  silently.</p>
</div></section>""" % (
        _stack([
            (srcln(T_PXC2, 281, "test_pxc2…py:281 · test_jaxtari_matches_jutari_per_frame_ram"),
             "The headline cross-check. Steps jaxtari live; loads the jutari fixture; compares "
             "RAM per frame."),
            (srcln(T_PXC2, 240, "test_pxc2…py:240 · _jaxtari_ram_per_frame"),
             "Boots jaxtari (60 NOOP + 4 RESET) and records the 128 B RAM after every action — "
             "the live side of the comparison."),
            (srcln(T_PXC2, 299, "test_pxc2…py:299 · if jax_ram != jul_ram"),
             "<b>The core check.</b> Byte-equality of the two ports' RAM at frame <code>i</code>; "
             "on mismatch builds a per-address diff and fails (%s)."
             % srcln(T_PXC2, 306, "L306")),
            (srcln(T_PXC2, 310, "test_pxc2…py:310 · …divergence_pattern_unchanged"),
             "Regression guard: the count of bytes still differing from xitari must equal the "
             "value pinned per ROM (all 0 today)."),
            (srcln(JDUMP, 132, "jutari_trace_dump.jl:132 · main"),
             "Produces the jutari fixture: same boot, same actions, records RAM per frame — the "
             "Julia side, generated once and committed."),
        ]),
        srcln(JDUMP, 132, "jutari_trace_dump.jl"),
        srcln(T_PXC2, 299, "L299"),
        srcln(T_PXC2, 306, "L306"),
        srcln(T_PXC2, 310, "the third test"),
    )

    pxcs = """
<section id="pxcs"><div class="wrap">
  <h2>PXC-S — screen conformance</h2>
  <p class="sub">Does the rendered 210&times;160 framebuffer match, pixel for pixel?</p>
  <p>RAM equality does not imply screen equality — the TIA renders pixels from register writes
  whose timing must be exact. PXC-S diffs the framebuffer per frame, both xitari↔jutari (from
  fixtures) and xitari↔jaxtari (rendered live), counting differing pixels.</p>
  %s
  <p><b>How to read it.</b> %s counts differing pixels per frame; each test asserts
  the worst frame is within a pinned threshold (%s — set to 0 once a game is
  pixel-exact). The live framebuffer comes from %s, which crops the TIA's internal
  buffer to the visible window.</p>
</div></section>""" % (
        _stack([
            (srcln(T_SCR, 219, "test_screen_conformance.py:219 · test_jutari_screen_matches_xitari"),
             "xitari fixture vs jutari fixture, per frame."),
            (srcln(T_SCR, 235, "test_screen_conformance.py:235 · test_jaxtari_screen_matches_xitari"),
             "xitari fixture vs jaxtari rendered live."),
            (srcln(T_SCR, 213, "test_screen_conformance.py:213 · _per_frame_diffs"),
             "<b>The core check.</b> Per frame: <code>(a[i] != b[i]).sum()</code> — the count of "
             "differing palette-index pixels; the test asserts the worst is ≤ the pin (%s)."
             % srcln(T_SCR, 227, "L227")),
            (srcln(ENV, 473, "stella_environment.py:473 · get_screen()"),
             "Crops <code>console.bus.tia.framebuffer</code> to the visible rows — the rendered "
             "output being diffed."),
        ]),
        srcln(T_SCR, 213, "_per_frame_diffs"),
        srcln(T_SCR, 75, "max_screen_diff"),
        srcln(ENV, 473, "get_screen()"),
    )

    pxc4 = """
<section id="pxc4"><div class="wrap">
  <h2>PXC4 — 6502 functional test</h2>
  <p class="sub">Is the CPU core a correct 6502, independent of any game?</p>
  <p>This runs Klaus Dormann's widely used 6502 functional test — an external ROM that
  exercises every opcode, addressing mode and flag — on a flat 64 KB memory, bypassing the TIA,
  RIOT and cartridge entirely. Success is a hard, unambiguous signal: the program only reaches
  its success address if every sub-test passed.</p>
  %s
  <p><b>How to read it.</b> The loop steps the CPU at %s and watches the program
  counter: reaching <code>KLAUS_SUCCESS_PC = 0x3469</code> (%s) means every sub-test
  passed; a PC stuck on a trap loop means a specific opcode is wrong, and the failure names the
  address to disassemble.</p>
</div></section>""" % (
        _stack([
            (srcln(T_K, 80, "test_pxc4_klaus_dormann.py · test_klaus_dormann…passes"),
             "Loads the ROM into flat 64 KB memory, sets PC to 0x0400, steps until success or stuck."),
            (srcln(T_K, 99, "test_pxc4_klaus_dormann.py:99 · _step_inner(state, memory)"),
             "Executes one 6502 instruction with no TIA/RIOT side effects — pure ISA."),
            (srcln(T_K, 102, "test_pxc4_klaus_dormann.py:102 · cur_pc == KLAUS_SUCCESS_PC"),
             "<b>The pass condition.</b> PC reaches 0x3469 (%s) ⇒ all opcodes/flags correct."
             % srcln(T_K, 49, "L49")),
            (srcln(CPU, 410, "m6502.py:410 · _step_inner"),
             "The shared instruction decoder/executor used by both the game path and this test."),
        ]),
        srcln(T_K, 99, "L99"),
        srcln(T_K, 49, "test_pxc4_klaus_dormann.py:49"),
    )

    core = """
<section id="core"><div class="wrap">
  <h2>Where the compared bytes come from — the emulator core</h2>
  <p>Each harness above bottoms out in the same port internals. This is the stack a single
  <code>step()</code> runs through, so a reviewer can follow a compared byte back to the CPU
  instruction and TIA tick that produced it.</p>
  %s
  <p>The Julia port mirrors this structure (<code>env_step!</code> / <code>get_ram</code> /
  <code>run_until_frame</code>); its fixtures are produced by %s. Because the two ports
  share neither code nor language, PXC2 agreement is independent corroboration of this stack.</p>
</div></section>""" % (
        _stack([
            (srcln(ENV, 87, "stella_environment.py:87 · reset(...)") + " → "
             + srcln(ENV, 191, "_boot_burn"),
             "Resets the console and burns the boot frames (60 NOOP + 4 RESET + any per-game "
             "starting actions) so the port starts where xitari starts."),
            (srcln(ENV, 375, "stella_environment.py:375 · step(action)"),
             "Applies the action to the bus, then runs one video frame."),
            (srcln(CON, 97, "console.py:97 · run_until_frame"),
             "Steps the CPU (up to a 25,000-instruction budget) until the TIA frame counter "
             "advances — one frame, including the partial/grey-frame case."),
            (srcln(CPU, 365, "m6502.py:365 · step") + " → "
             + srcln(CPU, 410, "_step_inner") + " + " + srcln(CPU, 382, "_tia_post_step"),
             "Fetch/decode/execute one 6502 instruction, then advance the TIA and RIOT by the "
             "cycles it consumed and resolve any WSYNC stall."),
            (srcln(CON, 49, "console.py:49 · console_reset"),
             "Reads the reset vector at $FFFC/$FFFD into PC — the boot entry the whole run hangs off."),
        ]),
        srcln(JDUMP, 132, "jutari_trace_dump.jl"),
    )

    reproduce = """
<section><div class="wrap">
  <h2>Reproduce</h2>
  <pre><code># regenerate an xitari reference trace
./tools/trace_dump --rom xitari/roms/pong.bin \\
  --actions tools/fixtures/actions/pong_noop_10.txt &gt; /tmp/pong.jsonl

# replay it against each port
python tools/check_trace.py --rom xitari/roms/pong.bin --trace /tmp/pong.jsonl
julia --project=jutari tools/check_trace.jl --rom xitari/roms/pong.bin --trace /tmp/pong.jsonl

# run the gates (PXC1/PXC2/PXC-S/PXC4 live)
cd jaxtari &amp;&amp; .venv/bin/python -m pytest -q tests/test_pxc1_conformance.py \\
  tests/test_pxc2_jaxtari_vs_jutari.py tests/test_pxc4_klaus_dormann.py
jaxtari/.venv/bin/pytest jaxtari/tests/test_screen_conformance.py   # ~23 min</code></pre>
</div></section>"""

    body = (intro + oracle + pxc1 + pxc2 + pxcs + pxc4 + core + reproduce)
    return page("conformance.html", "Conformance harness — code tour", body)


def build_methods():
    XS = "tools/xai_study/"

    def catalogue(rows, recdir, reccount):
        # rows: (method_html, script_basename, score_html)
        def key_of(s):
            return s.rsplit("/", 1)[-1].rsplit(".", 1)[0]
        def audit(s):
            key = key_of(s)
            tr = audit_triad(key)
            if tr is None:
                return "<span class='cite'>excluded</span>"
            F, S, Mm = tr
            af = audit_faith(key)
            ci = af[1] if af else 0.0
            ng = af[2] if af else None
            fcell = ("<b>%s</b> <span class='cite'>±%.3f</span>" % (_triad_cell(F), ci)
                     if F is not None else _triad_cell(F))
            games = (" <span class='cite'>· %s games</span>" % ng) if ng else ""
            return ("F %s / S %s / M %s%s"
                    % (fcell, _triad_cell(S), _triad_cell(Mm), games))
        body = "".join(
            "<tr><td>%s</td><td>%s</td><td>%s</td><td>%s</td><td>%s</td></tr>"
            % (m, srcln_or_src(XS + s), sc, audit(s),
               '<a href="m_%s.html">explain &amp; figure →</a>' % key_of(s)) for m, s, sc in rows)
        head = ('<table class="tbl"><tr><th>Method (reference)</th>'
                '<th>Implementation</th><th>Score description</th>'
                '<th><a href="#e6">Audit triad (F / S / M)</a></th>'
                '<th>Page</th></tr>'
                '%s</table>' % body)
        rec = ('<p class="caption">Records: %s — <b>%d</b> committed §R JSON+npz.</p>'
               % (src(XS + recdir, recdir), reccount))
        return head + TRIAD_LEGEND + rec

    def srcln_or_src(path):  # link a file by its basename label
        return src(path, path.rsplit("/", 1)[-1])

    PHASE_A = [
        ("<b>A1</b> connectomics / data-flow graph", "phaseA_kording/A1_connectomics.jl",
         "precision/recall + graph-edit-distance vs the true read/write graph"),
        ("<b>A2</b> single-unit lesions", "phaseA_kording/A2_lesions.jl",
         "rank-correlation of importance with the unit's true role; spurious-specific count"),
        ("<b>A3</b> tuning curves", "phaseA_kording/A3_tuning.jl",
         "spurious-tuning rate (strongly-tuned units whose tuning ≠ true role)"),
        ("<b>A4</b> spike-word / pairwise correlations", "phaseA_kording/A4_correlations.jl",
         "weak-pairwise / strong-global structure reproduced vs true coupling"),
        ("<b>A5</b> local field potentials", "phaseA_kording/A5_lfp.jl",
         "%-variance that is the known clocks (frame/scanline) → epiphenomenal"),
        ("<b>A6</b> Granger causality", "phaseA_kording/A6_granger.jl",
         "false-edge / missed-edge rate vs the true data-flow"),
        ("<b>A7</b> dim-reduction (NMF/PCA)", "phaseA_kording/A7_dimred.jl",
         "matched-component fraction vs known signals (clock, R/W, vsync)"),
        ("<b>A8</b> whole-state recording", "phaseA_kording/A8_wholestate.jl",
         "descriptive baseline"),
    ]
    PHASE_B = [
        ("Vanilla gradient <span class='cite'>Simonyan et al. 2014</span>",
         "phaseB_attribution/saliency.jl",
         "corr + deletion/insertion AUC + precision@k vs true causal top-k"),
        ("Grad×Input / DeepLIFT <span class='cite'>Shrikumar et al. 2017</span>",
         "phaseB_attribution/gradxinput.jl", "as above + completeness where defined"),
        ("Guided Backprop <span class='cite'>Springenberg et al. 2015</span>",
         "phaseB_attribution/guided_backprop.jl", "as above + the Adebayo et al. 2018 sanity check"),
        ("SmoothGrad <span class='cite'>Smilkov et al. 2017</span>",
         "phaseB_attribution/smoothgrad.jl", "noise-averaged saliency; corr + del/ins"),
        ("<b>Integrated Gradients</b> <span class='cite'>Sundararajan et al. 2017</span>",
         "phaseB_attribution/ig_baseline_sweep.jl", "corr + del/ins + completeness; baseline sweep"),
        ("Expected Gradients <span class='cite'>Erion et al. 2021 (NMI)</span>",
         "phaseB_attribution/expected_gradients.jl", "baseline-averaged IG; as above"),
        ("Occlusion <span class='cite'>Zeiler &amp; Fergus 2014</span>",
         "phaseB_attribution/occlusion.jl", "del/ins AUC ≈ coarse intervention oracle"),
        ("Extremal / meaningful perturbation <span class='cite'>Fong &amp; Vedaldi 2017; Fong et al. 2019</span>",
         "phaseB_attribution/perturbation.jl", "learned minimal mask; IoU vs true causal set"),
        ("RISE <span class='cite'>Petsiuk et al. 2018</span>",
         "phaseB_attribution/rise.jl", "randomized-mask saliency (N=500 masks); corr + del/ins"),
        ("LIME <span class='cite'>Ribeiro et al. 2016</span>",
         "phaseB_attribution/lime.jl", "local linear weights; corr vs true; stability"),
        ("KernelSHAP / Shapley <span class='cite'>Lundberg &amp; Lee 2017; Štrumbelj &amp; Kononenko 2014</span>",
         "phaseB_attribution/kernelshap.jl", "Shapley values; corr vs true; convergence vs compute"),
        ("On-distribution counterfactual <span class='cite'>cf. Olson 2021; Atrey 2020</span>",
         "phaseB_attribution/counterfactual.jl", "minimal valid edit: validity + minimality vs true minimal set"),
        ("<b>N/A audit</b>: Grad-CAM/++, attention rollout, VIPER "
         "<span class='cite'>Selvaraju 2017; Abnar &amp; Zuidema 2020; Bastani 2018</span>",
         "phaseB_attribution/na_audit.jl", "recorded as <i>does not apply</i> (needs NN layers / a policy)"),
    ]
    PHASE_C = [
        ("Activation patching / causal mediation <span class='cite'>Vig et al. 2020; ROME, Meng et al. 2022</span>",
         "phaseC_mechanistic/activation_patching.jl", "recovered effect vs the exact patch; site P/R vs true data-flow"),
        ("Interchange interventions / DAS <span class='cite'>Geiger et al. 2021, 2023</span>",
         "phaseC_mechanistic/das.jl", "interchange accuracy; alignment vs the true variable"),
        ("Attribution / edge patching <span class='cite'>Nanda 2023; Syed et al. 2023</span>",
         "phaseC_mechanistic/attribution_patching.jl", "approx error vs true patching; edge P/R"),
        ("Path patching / IOI circuit <span class='cite'>Wang et al. 2022; Goldowsky-Dill et al. 2023</span>",
         "phaseC_mechanistic/path_patching.jl", "circuit precision/recall vs the true routine"),
        ("ACDC — automatic circuit discovery <span class='cite'>Conmy et al. 2023</span>",
         "phaseC_mechanistic/acdc.jl", "edge P/R + scrubbing-preserved performance vs true data-flow"),
        ("Sparse autoencoders <span class='cite'>Cunningham et al. 2023; Bricken et al. 2023; Templeton et al. 2024</span>",
         "phaseC_mechanistic/sae.jl", "feature↔known-variable match (F1/MI) + causal use + monosemanticity"),
        ("NMF/PCA dictionaries", "phaseC_mechanistic/dictionaries.jl",
         "matched-component fraction vs known variables"),
        ("Causal scrubbing <span class='cite'>Chan et al. 2022</span>",
         "phaseC_mechanistic/causal_scrubbing.jl", "scrubbing-preserved performance vs the true routine"),
        ("Linear probing + control tasks <span class='cite'>Alain &amp; Bengio 2017; Hewitt &amp; Liang 2019</span>",
         "phaseC_mechanistic/linear_probing.jl", "accuracy <b>and</b> selectivity (probe − control) → present-vs-used gap"),
        ("Logit / tuned lens <span class='cite'>nostalgebraist 2020; Belrose et al. 2023</span>",
         "phaseC_mechanistic/logit_lens.jl", "readout fidelity vs the true intermediate value"),
    ]
    ORACLE = [
        ("Intervention oracle — the primary ground truth", "ground_truth/oracle_intervene.jl",
         "occlude/clamp/resample a cause <code>u</code>, re-run bit-exact, record exact |Δy(u)|"),
        ("Gradient oracle (content path)", "ground_truth/oracle_grad.jl",
         "∂y/∂u + Integrated Gradients through the differentiable substrate (content outputs only)"),
        ("Cross-check", "ground_truth/oracle_xcheck.jl",
         "correlation of intervention vs gradient; disagreement is reported, not hidden"),
    ]
    T3 = [
        ("Import candidate labels", "t3/import_labels.py",
         "OCAtari / AtariARI RAM→concept candidates"),
        ("Verify by intervention", "t3/verify_labels.jl",
         "set the byte, re-render, confirm the object moves → upgrades to verified-causal"),
        ("Discover new labels", "t3/discover_labels.jl",
         "RAM↔framebuffer correlation + intervention sweeps"),
    ]
    INFRA = [
        ("common/results.py", "tools/xai_study/common/results.py", "writes/reads the §R record schema"),
        ("common/jutari_oracle.jl", "tools/xai_study/common/jutari_oracle.jl", "the intervention/gradient oracle on the jutari substrate"),
        ("common/replay.py", "tools/xai_study/common/replay.py", "deterministic replay-to-state (the <code>f&lt;start&gt;+&lt;window&gt;</code> encoding)"),
        ("common/seeds.py", "tools/xai_study/common/seeds.py", "the single seed=0 source"),
        ("common/game_set.json", "tools/xai_study/common/game_set.json", "the labeled game set (42 scored games; 6-game core is a subset)"),
        ("repro/make_hash_tables.py", "tools/xai_study/repro/make_hash_tables.py", "SHA-256 ROM + action-stream hashes (verify with --verify)"),
    ]

    diagram = """  ROM  (AutoROM, SHA-256 verified — not redistributed)
    │   jutari substrate · seed 0 · state f120+30 · games: labeled (42 scored)
    ▼
  ground_truth/oracle_intervene.jl ── exact |Δy(u)| ──▶  the §1 oracle  (T1 causal truth)
    │
    ├─ phaseA_kording/A1..A8.jl       neuroscience battery
    ├─ phaseB_attribution/*.jl        12 XAI methods + N/A audit
    └─ phaseC_mechanistic/*.jl        10 mechanistic-interp methods
         each runner scores its output vs the oracle on the triad  F ∧ S ∧ M
         └─▶ writes a §R record   out/<phase>/<exp>_<game>.json  (+ .npz)
    ▼
  compare/leaderboard.py    ── pure read of every record ──▶  faithfulness × plausibility
  compare/benchmark/run.py  ── ROM-free scoring of a new method against the committed oracle"""

    body = """
<header class="hero"><div class="wrap">
  <h1>Paper 2 — method catalogue &amp; execution stack</h1>
  <p class="lead">Every interpretability method in the benchmark, with a link to its
  implementation, its reference, and the score it is graded on — plus how a run executes,
  what it writes, and where the records live. This is the Paper-2 counterpart of the
  <a href="conformance.html">conformance code tour</a>.</p>
  <p style="margin-top:12px"><a href="#stack">Execution stack</a> ·
  <a href="#oracle">Oracle &amp; T3</a> · <a href="#phaseA">Phase A</a> ·
  <a href="#phaseB">Phase B (attribution)</a> · <a href="#phaseC">Phase C (mechanistic)</a> ·
  <a href="#e6">Leaderboard &amp; benchmark</a></p>
</div></header>

<section id="stack"><div class="wrap">
  <h2>How a measurement runs</h2>
  <p>Because the VCS is fully known and exactly intervenable, every explanation is scored
  against the truth. The <b>intervention oracle</b> records the exact causal effect
  |Δy(u)| of each candidate cause by clamping it and re-running bit-exact. Each method
  runner then produces its own attribution/circuit and is graded against that oracle on the
  correctness triad — <b>F</b> faithful (true causes), <b>S</b> sufficient (predicts held-out
  interventions), <b>M</b> minimal/right-level. Runners are Julia on the jutari substrate
  (jaxtari eager is ≈205× slower), <code>seed = 0</code>, on the 42 scored games,
  inside the Paper-1 bit-exact horizon.</p>
  <pre><code>%s</code></pre>
  <p>Every runner writes a self-describing <b>§R record</b> per game/regime —
  <code>{paper, phase, method, game, state, target_output, metric_name, value, ci, n,
  seed, where, commit, oracle_ref, timestamp}</code> plus an <code>extra{}</code> block
  carrying the exact <code>oracle_abs_delta_per_cause</code> map and the triad
  <code>{F,S,M}</code>. That is what makes the leaderboard a <i>pure read</i> and the
  benchmark ROM-free.</p>
  <h3>Shared infrastructure</h3>
  <table class="tbl"><tr><th>Module</th><th>Role</th></tr>%s</table>
</div></section>

<section id="oracle"><div class="wrap">
  <h2>E1 · the ground-truth oracle &amp; E2 · T3 labels</h2>
  <p class="sub">The instrument everything is scored against, and the game-concept labels.</p>
  %s
  <p class="caption">Oracle records: %s — <b>3</b>. T3 records: %s — <b>17</b>.</p>
</div></section>

<section id="phaseA"><div class="wrap">
  <h2>Phase A — the Jonas &amp; Kording battery (quantified)</h2>
  <p class="sub">Classical neuroscience methods, scored against the true register-transfer
  account. The calibration baseline: rich structure, low faithfulness.</p>
  %s
</div></section>

<section id="phaseB"><div class="wrap">
  <h2>Phase B — attribution / XAI methods</h2>
  <p class="sub">One runner per method; each saliency/attribution map scored against the
  oracle. References are the methods' original papers.</p>
  %s
</div></section>

<section id="phaseC"><div class="wrap">
  <h2>Phase C — mechanistic interpretability</h2>
  <p class="sub">The state trajectory is the “activations”, the program's data-flow is the
  “circuit” — both known exactly, so recovered structure is scored against the truth.</p>
  %s
</div></section>

<section id="e6"><div class="wrap">
  <h2>E6 — leaderboard &amp; the ROM-free benchmark</h2>
  <table class="tbl"><tr><th>Step</th><th>Implementation</th><th>Output</th></tr>
    <tr><td>Cross-tradition leaderboard (pure read of all records)</td><td>%s</td>
      <td>%s</td></tr>
    <tr><td>Headline faithful-vs-plausible demo</td><td>%s</td><td>%s</td></tr>
    <tr><td>Packaged benchmark — score a new method, no ROM needed</td><td>%s</td>
      <td>%s</td></tr>
  </table>
  <p>The leaderboard re-orients each record's faithfulness onto the headline plot
  (faithfulness X vs a transparent plausibility proxy Y) and runs an embedded self-check;
  it never re-runs an experiment. The benchmark scores one method end-to-end against the
  committed oracle records — a third party needs no ROM.</p>
</div></section>

<section><div class="wrap">
  <h2>Reproduce</h2>
  <pre><code># the oracle, then any method runner (Julia on the jutari substrate, seed 0)
julia --project=jutari tools/xai_study/ground_truth/oracle_intervene.jl --game pong
julia --project=jutari tools/xai_study/phaseB_attribution/ig_baseline_sweep.jl --games core
julia --project=jutari tools/xai_study/phaseC_mechanistic/activation_patching.jl --games core

# aggregate (pure reads — no ROM) and score a new method
python3 tools/xai_study/compare/leaderboard.py
python3 tools/xai_study/compare/benchmark/run.py --method magnitude_proxy</code></pre>
  <p class="caption">Full per-phase command list:
  %s.</p>
</div></section>
""" % (
        diagram,
        "".join("<tr><td>%s</td><td>%s</td></tr>" % (src(p, n), d) for n, p, d in INFRA),
        ('<table class="tbl"><tr><th>Step</th><th>Implementation</th><th>What it computes</th></tr>'
         + "".join("<tr><td>%s</td><td>%s</td><td>%s</td></tr>"
                   % (n, src(XS + s, s.rsplit("/", 1)[-1]), d) for n, s, d in (ORACLE + T3))
         + "</table>"),
        src(XS + "ground_truth/out", "ground_truth/out"),
        src(XS + "t3/out", "t3/out"),
        catalogue(PHASE_A, "phaseA_kording/out", 54),
        catalogue(PHASE_B, "phaseB_attribution/out", 166),
        catalogue(PHASE_C, "phaseC_mechanistic/out", 72),
        src(XS + "compare/leaderboard.py", "compare/leaderboard.py"),
        src(XS + "compare/out/leaderboard.json", "compare/out/leaderboard.json"),
        src(XS + "compare/faithful_demo.py", "compare/faithful_demo.py"),
        src(XS + "compare/out/faithful_demo.json", "compare/out/faithful_demo.json"),
        src(XS + "compare/benchmark/run.py", "compare/benchmark/run.py"),
        src(XS + "compare/benchmark/out", "compare/benchmark/out (14)"),
        link("https://github.com/akmaier/UnderstandingVCS/blob/main/xai_paper/xai_2_interpretability/REPRODUCIBILITY.md",
             "REPRODUCIBILITY.md §3"),
    )
    return page("methods.html", "Paper 2 — method catalogue", body)


# The cross-method audit is read from the site store (docs/site_data.json),
# keyed by the SITE method key used everywhere on the pages.
def audit_row(key):
    return SITE["methods"].get(key)


def audit_faith(key):
    """(faithfulness, ci95, n_games, n_records) from the store, or None."""
    r = audit_row(key)
    if not r or r.get("F") is None:
        return None
    return (r["F"], r.get("F_ci") or 0.0, r.get("n_games"), r.get("n_records"))


def audit_triad(key):
    """(F, S, M) per-method means from the store, or None per axis where the paper
    does not define that axis. Returns None if the method has no row at all. F is
    the canonical, always-populated `faithfulness`; S and M are null for the
    black-box methods and render as n/a."""
    r = audit_row(key)
    if not r:
        return None
    return (r.get("F"), r.get("S"), r.get("M"))


def _triad_cell(val):
    """Render one triad value as a 3-decimal number, or 'n/a' when the paper does
    not define that axis for this method (null in leaderboard.json)."""
    if val is None:
        return "<span class='cite'>n/a</span>"
    return "%.3f" % val


TRIAD_LEGEND = (
    "<p class=\"caption\"><b>F</b> faithfulness (scored vs the oracle for every method) · "
    "<b>S</b> sufficiency (held-out predictive; reported for the predictive Phase-B/C methods) · "
    "<b>M</b> minimality (true-minimal-set / named-set; where the method names a cause set) — "
    "<b>n/a</b> otherwise, per the paper's F&nbsp;&and;&nbsp;S&nbsp;&and;&nbsp;M triad.</p>")


_PHASE_LABEL = {"A": "Phase A · neuroscience battery", "B": "Phase B · attribution / XAI",
                "C": "Phase C · mechanistic interpretability", "NA": "recorded as not-applicable"}
_PHASE_ANCHOR = {"A": "phaseA", "B": "phaseB", "C": "phaseC", "NA": "phaseB"}
_RECDIR = {"A": "phaseA_kording", "B": "phaseB_attribution", "NA": "phaseB_attribution",
           "C": "phaseC_mechanistic"}


_MATRIX = {"A1_connectomics", "A4_correlations", "A6_granger", "path_patching", "acdc"}
_SCATTER = {"activation_patching", "attribution_patching", "das"}


def _hexlab(i):
    return "$%02X" % int(i)


_FP_BAND = {}
def _fp_band():
    """Per pong cell: (% of footprint pixels in the top score band, total px)."""
    if _FP_BAND:
        return _FP_BAND
    try:
        import numpy as np
        A = os.path.join(HERE, "assets", "methods")
        cells = [int(x) for x in open(os.path.join(A, "fp_pong_cells.txt"))]
        fp = np.frombuffer(open(os.path.join(A, "fp_pong.raw"), "rb").read(),
                           np.float32).reshape(len(cells), 210, 160)
        for i, c in enumerate(cells):
            tot = int((fp[i] > 0).sum())
            _FP_BAND[c] = (round(100 * int((fp[i][:33] > 0).sum()) / max(tot, 1)), tot)
    except Exception:
        pass
    return _FP_BAND


def _phaseB_reading(meth):
    """A per-method, data-driven explanation of what its example figure's causal
    region shows (which output, which cells, why the score/paddle appear), plus
    the shared footprint-proxy caveat. Returns '' for non-Phase-B methods."""
    if meth["phase"] != "B":
        return ""
    import numpy as np
    import re as _re
    b = os.path.join(REPO, "tools", "xai_study", "phaseB_attribution", "out", meth["record"])
    try:
        rec = _json.load(open(b + ".json"))
        npz = dict(np.load(b + ".npz", allow_pickle=True))
    except Exception:
        return ""
    ex = rec.get("extra", {})
    note = ex.get("output_note", "")
    ci = ex.get("content_ram_index")
    is_score = "score@" in note
    if is_score:
        mm = _re.search(r"score@ram\[(\d+)\]", note)
        oc = int(mm.group(1)) if mm else None
        outdesc = ("the <b>score</b> (score@RAM&nbsp;%s)" % _hexlab(oc)) if oc else "the <b>score</b>"
    elif ci is not None:
        outdesc = ("the content of <b>RAM&nbsp;%s</b> (byte&nbsp;%d) — the most causally-active "
                   "concept byte at this state" % (_hexlab(ci), ci))
    else:
        outdesc = "a single content byte"
    orac = np.abs(np.asarray(npz.get("oracle_abs_delta", []), float))
    names = ex.get("cause_names", [])
    per = {}
    for k, nm in enumerate(names):
        m = _re.search(r"ram\[(\d+)\]", str(nm))
        if m and k < len(orac):
            per[int(m.group(1))] = per.get(int(m.group(1)), 0.0) + float(orac[k])
    top = [c for c, v in sorted(per.items(), key=lambda x: -x[1]) if v > 0][:3]
    band = _fp_band()

    def phrase(c):
        s = band.get(c, (0, 0))[0]
        if s >= 5:
            return ("RAM&nbsp;%s (%d%% of its footprint sits in the score band, the rest in the "
                    "play area)" % (_hexlab(c), s))
        return "RAM&nbsp;%s (the play area — ball / paddles)" % _hexlab(c)

    tops = "; ".join(phrase(c) for c in top) if top else "no candidate cell"
    score_cells = [c for c in top if band.get(c, (0, 0))[0] >= 5]
    bleed = ""
    if score_cells and not is_score:
        who = "RAM&nbsp;" + "/".join(_hexlab(c) for c in score_cells)
        bleed = (" The <b>score digits</b> appear in the region because %s reach%s them: perturbing "
                 "%s over the 30-frame NOOP window changes the game outcome, and hence the score — a "
                 "<i>downstream</i> effect, not direct rendering." %
                 (who, "es" if len(score_cells) == 1 else "", "it" if len(score_cells) == 1 else "them"))
    missing = ""
    if is_score:
        missing = (" Because it explains the score, its only true-cause is %s, so the region covers "
                   "the score and the ball but <b>not the paddle</b>: the paddle cell (RAM&nbsp;$36) "
                   "is not causal for the score, so it is legitimately absent." %
                   ("RAM&nbsp;" + "/".join(_hexlab(c) for c in top)))
    return """
<section><div class="wrap">
  <h2>Reading this example's causal region</h2>
  <p>This example explains %s. Its strongest true-cause%s: %s.%s%s</p>
</div></section>""" % (outdesc, "s are" if len(top) != 1 else " is", tops, bleed, missing)


def _method_caption(meth):
    ph, k = meth["phase"], meth["key"]
    if ph == "B":
        return ("<b>Top row</b> (image domain, as in Paper 1): the game frame, then the oracle's "
                "<b>true causal region</b> and this method's <b>attributed region</b> — each painted "
                "onto the frame through the screen footprint of the RAM cells it implicates "
                "(brighter = more important). A faithful method's heat matches the oracle's. "
                "<b>Bottom</b>: per-cell importance — oracle "
                "(<span style='color:var(--accent-2)'>green</span>) vs method "
                "(<span style='color:var(--accent)'>blue</span>) — and the deletion/insertion "
                "faithfulness curves (perturb the ranked causes and watch the output move). "
                "<i>Note:</i> the image-domain overlay footprints are illustrative, computed on the "
                "pre-redesign boot frame; the bars, curves and all reported numbers come from the "
                "re-run records on the shared gameplay states.")
    if k in _MATRIX:
        return ("Two adjacency matrices over the candidate RAM cells: the <b>true</b> data-flow "
                "graph and the graph this method <b>recovered</b>. A bright cell (row = cause, "
                "column = effect) is an edge; the difference between the two panels is the error.")
    if k in _SCATTER:
        return ("Each point is one intervention site: its <b>exact causal effect</b> from the "
                "oracle (x) against the method's <b>recovered/approximate effect</b> (y). Points on "
                "the dashed diagonal mean the method recovered the true effect.")
    if k == "A3_tuning":
        return ("Each point is a RAM cell: its <b>true causal importance</b> (x) against its "
                "<b>tuning strength</b> to a game variable (y). "
                "<span style='color:var(--bad)'>Red</span> points are strongly tuned yet not "
                "causal — the trap the metric measures.")
    if k == "A2_lesions":
        return ("Left: the frame. Middle: each cell's lesion importance painted on the screen via "
                "its footprint. Right: lesion importance vs the cell's true causal role.")
    if k == "linear_probing":
        return ("Per labelled RAM cell, the probe's <b>selectivity</b> (accuracy minus a control "
                "task). <span style='color:var(--bad)'>Red</span> bars are cells that are "
                "decodable but <i>not causally used</i> — present ≠ used.")
    if ph == "A":
        return ("Left: the frame. Right: this method's per-cell/per-component result against the "
                "ground-truth importance, with the RAM cells labelled.")
    if ph == "C":
        return ("Left: the frame. Right: the recovered structure/effect against the ground truth "
                "(matched components or preserved behaviour), with the RAM cells labelled.")
    return "Left: a game frame for context. Right: why these methods do not apply to the VCS."


# ---------------------------------------------------------------------------
# Small sortable-table helper (used by method + per-game detail pages). Clicking
# a header sorts by that column; numeric columns sort numerically, n/a last.
# ---------------------------------------------------------------------------
SORT_JS = """<script>
document.addEventListener('click',function(e){
  var th=e.target.closest('th[data-sort]'); if(!th) return;
  var tbl=th.closest('table'), tb=tbl.tBodies[0], idx=Array.from(th.parentNode.children).indexOf(th);
  var dir=th.getAttribute('data-dir')==='asc'?'desc':'asc';
  Array.from(tbl.querySelectorAll('th')).forEach(function(h){h.removeAttribute('data-dir');});
  th.setAttribute('data-dir',dir);
  var num=th.getAttribute('data-sort')==='num';
  var rows=Array.from(tb.rows);
  rows.sort(function(a,b){
    var x=a.cells[idx].getAttribute('data-v'), y=b.cells[idx].getAttribute('data-v');
    if(num){var nx=parseFloat(x),ny=parseFloat(y);
      var ax=isNaN(nx),ay=isNaN(ny); if(ax&&ay)return 0; if(ax)return 1; if(ay)return -1;
      return dir==='asc'?nx-ny:ny-nx;}
    return dir==='asc'?String(x).localeCompare(y):String(y).localeCompare(x);
  });
  rows.forEach(function(r){tb.appendChild(r);});
});
</script>"""

SORT_CSS = ("<style>table.sortable th[data-sort]{cursor:pointer;user-select:none}"
            "table.sortable th[data-sort]::after{content:' \\2195';opacity:.4;font-size:.8em}"
            "table.sortable th[data-dir=asc]::after{content:' \\2191';opacity:.9}"
            "table.sortable th[data-dir=desc]::after{content:' \\2193';opacity:.9}"
            "td.num{text-align:right;font-variant-numeric:tabular-nums}</style>")


def _fcell(x):
    """A numeric table cell with a data-v attribute for sorting (n/a sorts last)."""
    if x is None:
        return '<td class="num" data-v="nan"><span class="cite">n/a</span></td>'
    return '<td class="num" data-v="%.4f">%.3f</td>' % (x, x)


def _method_pergame_note(F, Fpos):
    """A one-line qualitative note for a method's per-game row, where notable."""
    if F is None:
        return ""
    if Fpos is not None and Fpos <= 0.02:
        return "position gradient vanishes"
    if F >= 0.85:
        return "recovers the true causes"
    if F <= 0.05:
        return "no true-cause signal"
    if Fpos is not None and F is not None and Fpos >= 0.5 and Fpos >= F:
        return "holds up on position"
    return ""


def build_method_results_section(key):
    """A sortable 'Results per game' table for one method, from the store."""
    m = SITE["methods"].get(key)
    if not m or not m.get("per_game"):
        return ""
    rows = []
    for game in sorted(m["per_game"], key=lambda g: -(m["per_game"][g]["F"] or -1)):
        pg = m["per_game"][game]
        note = _method_pergame_note(pg.get("F"), pg.get("F_position"))
        rows.append(
            '<tr><td data-v="%s"><a href="g_%s.html">%s</a></td>%s%s%s'
            '<td data-v="%s"><span class="cite">%s</span></td></tr>'
            % (esc(game_disp(game)), game, esc(game_disp(game)),
               _fcell(pg.get("F")), _fcell(pg.get("F_content")), _fcell(pg.get("F_position")),
               esc(note), esc(note)))
    table = ('<table class="tbl sortable"><thead><tr>'
             '<th data-sort="str">Game</th>'
             '<th data-sort="num">F (all)</th>'
             '<th data-sort="num">content-F</th>'
             '<th data-sort="num">position-F</th>'
             '<th>Note</th></tr></thead><tbody>%s</tbody></table>' % "".join(rows))
    return """
<section><div class="wrap">
  <h2>Results per game</h2>
  <p class="sub">This method's faithfulness on each of the %d scored games (all-regime F, and the
  content vs position split). Click a header to sort. Every number is read from
  <a href="%sdocs/site_data.json"><code>site_data.json</code></a>
  (<code>methods.%s.per_game</code>).</p>
  %s%s
  %s
</div></section>""" % (len(m["per_game"]), BLOB, esc(key), SORT_CSS, SORT_JS, table)


def build_method_page(meth):
    rec = {}
    rpath = os.path.join(REPO, "tools", "xai_study", _RECDIR[meth["phase"]], "out",
                         meth["record"] + ".json")
    try:
        rec = _json.load(open(rpath))
    except Exception:
        pass
    v = rec.get("value")
    vs = ("%.3f" % v) if isinstance(v, (int, float)) else str(v)
    score = ("<b>%s = %s</b> — this example only (%s, state %s); the audit aggregate is below."
             % (esc(rec.get("metric_name", "score")), esc(vs), esc(meth["game"]),
                esc(rec.get("state", "—")))) if rec else ""
    recdir = "tools/xai_study/%s/out" % _RECDIR[meth["phase"]]
    meta = [
        ("Implementation", src(meth["script"])),
        ("Reference", esc(meth["ref"])),
        ("Record", src(recdir + "/" + meth["record"] + ".json", meth["record"] + ".json")),
        ("All records", src(recdir, _RECDIR[meth["phase"]] + "/out")),
    ]
    metahtml = "".join("<dt>%s</dt><dd>%s</dd>" % (k, val) for k, val in meta)

    # "In the audit" — the method's real entry in the cross-method leaderboard
    af = audit_faith(meth["key"])
    tr = audit_triad(meth["key"])
    ar = audit_row(meth["key"])
    lb = "tools/xai_study/compare/out/leaderboard.json"
    if af:
        faith, ci, ng, nr = af
        F, S, Mm = tr
        plaus = ar.get("plausibility_proxy")
        trad = ar.get("tradition")
        fsmall = ("faithfulness vs oracle (mean over %s games, &plusmn;%.3f CI95)" % (ng, ci)) \
            if F is not None else "faithfulness vs oracle"
        bign = ('<div class="bignum">'
                '<div class="b"><strong>%s</strong><small>F — %s</small></div>'
                '<div class="b"><strong>%s</strong><small>S — sufficiency: held-out predictive '
                '(n/a where the paper does not define this axis)</small></div>'
                '<div class="b"><strong>%s</strong><small>M — minimality: true-minimal-set / '
                'named-set (n/a otherwise)</small></div>'
                '<div class="b"><strong>%s</strong><small>committed records aggregated</small></div>'
                '<div class="b"><strong>%.2f</strong><small>human-plausibility proxy</small></div>'
                '</div>' % (_triad_cell(F), fsmall, _triad_cell(S), _triad_cell(Mm), nr,
                            plaus if plaus is not None else 0))
        audit_html = """
<section><div class="wrap">
  <h2>In the audit</h2>
  <p>This is the method's entry in the actual cross-method audit — scored on the paper's
  correctness triad, each axis a <b>mean over all %s scored games</b> (%s committed §R records), not
  the single example shown above. Tradition: <b>%s</b>. The example figure (Pong) is one of those
  records.</p>
  %s
  %s
  <p class="caption">Source: %s · the whole leaderboard is on the
  <a href="methods.html#e6">methods page</a> and the
  <a href="paper2.html">Paper&nbsp;2 audit</a>.</p>
</div></section>""" % (ng, nr, esc(str(trad)), bign, TRIAD_LEGEND, src(lb, "leaderboard.json"))
    else:
        audit_html = """
<section><div class="wrap">
  <h2>In the audit</h2>
  <p>Recorded but <b>excluded from the faithfulness leaderboard</b>: these methods have no
  applicable causes on the VCS, so a faithfulness score would be meaningless. See the
  <a href="methods.html#e6">leaderboard</a> and the <a href="paper2.html">Paper&nbsp;2 audit</a>.</p>
  <p class="caption">Source: %s.</p>
</div></section>""" % src(lb, "leaderboard.json")
    # Long-form prose (What it does? / How it's scored), with graceful fallback
    # to the short one-liners if a key is not yet covered.
    about = M.P2_METHOD_ABOUT.get(meth["key"]) or esc(meth["what"])
    howscored = M.P2_METHOD_HOWSCORED.get(meth["key"])
    if not howscored:
        # Fallback one-liner carries {F}/{F_content}/{F_position}/{M} placeholders —
        # fill them from the store so no number is ever hardcoded in the fallback.
        raw = M.P2_METHOD_SCORED.get(meth["key"], "")
        mrow = SITE["methods"].get(meth["key"], {})
        howscored = raw.format(F=_num(mrow.get("F")), F_content=_num(mrow.get("F_content")),
                               F_position=_num(mrow.get("F_position")), M=_num(mrow.get("M")))
    results_section = build_method_results_section(meth["key"])

    body = """
<header class="hero"><div class="wrap">
  <span class="venue" style="color:var(--accent-2);font-weight:600">%s</span>
  <h1>%s</h1>
  <p class="lead">%s</p>
  <p style="margin-top:10px"><a href="methods.html#%s">← back to the method catalogue</a></p>
</div></header>

<section><div class="wrap">
  <h2>What it does?</h2>
  <p>%s</p>
</div></section>

<section><div class="wrap">
  <div class="fig" style="max-width:1040px;margin:0 auto">
    <a href="assets/methods/%s.png" target="_blank"><img src="assets/methods/%s.png" alt="%s result"></a>
  </div>
  <p class="caption">%s %s</p>
</div></section>

%s

<section><div class="wrap">
  <h2>How it's scored</h2>
  <p>%s</p>
  <p class="caption">The score is measured against the §1 intervention oracle — never against
  another interpretability method. F (faithful) is always vs the oracle; see the
  <a href="methods.html#stack">execution stack</a>. The exact F / S / M numbers for this method
  are in the <b>In the audit</b> box below.</p>
</div></section>

%s

%s

<section><div class="wrap">
  <dl class="meta" style="margin-top:0">%s</dl>
  <p class="caption" style="margin-top:14px">The figure is generated from the committed record by
  <a href="%sdocs/gen_method_figures.py"><code>docs/gen_method_figures.py</code></a>; the game frame
  and each RAM cell's screen footprint are produced by
  <a href="%sdocs/render_scenes.jl"><code>render_scenes.jl</code></a> /
  <a href="%sdocs/cell_footprints.jl"><code>cell_footprints.jl</code></a>.</p>
</div></section>
""" % (esc(_PHASE_LABEL[meth["phase"]]), esc(meth["title"]), esc(meth["ref"]),
       _PHASE_ANCHOR[meth["phase"]], about, meth["key"], meth["key"], esc(meth["title"]),
       _method_caption(meth), score, _phaseB_reading(meth),
       howscored, audit_html, results_section, metahtml, BLOB, BLOB, BLOB)
    return page("m_%s.html" % meth["key"], meth["title"] + " — Paper 2 method", body)


def build_ground_truth():
    """The Ground Truth ROMs page: lay explainers for T1/T2/T3 and F/S/M, plus a
    per-game card grid driven by docs/groundtruth_data.json + rendered screenshots."""
    import json
    data = json.load(open(os.path.join(HERE, "groundtruth_data.json")))
    disp = game_disp

    def is_pos(c):
        c = c.lower()
        return any(p in c for p in ("_x", "_y", ".xy", "position", "column"))

    labeled = [g for g in data if data[g]["labeled"]]
    accepted = [g for g in data if data[g].get("accepted")]
    posreg = [g for g in data if data[g].get("position_regime")]
    scored = [g for g in data if data[g].get("scored")]

    def rank(g):
        d = data[g]
        tier = 0 if d.get("position_regime") else 1 if d.get("accepted") else 2 if d["labeled"] else 3
        return (tier, g)

    cards = []
    for g in sorted(data, key=rank):
        d = data[g]
        rel = "assets/groundtruth/%s.png" % g
        has_img = os.path.exists(os.path.join(HERE, "assets", "groundtruth", g + ".png"))
        thumb = ('<img src="%s" alt="%s screen">' % (rel, esc(disp(g)))
                 if has_img else '<div class="noimg">screenshot pending</div>')
        obadge = {"both": "AtariARI + OCAtari", "OCAtari": "OCAtari",
                  "none": "no external label"}[d["origin"]]
        ocls = {"both": "ok", "OCAtari": "mid", "none": "na"}[d["origin"]]
        if d["labeled"]:
            t3 = ("<b>T3:</b> %d of %d imported labels verified causally · %d move a sprite"
                  % (d["n_verified"], d["n_candidates"], d["n_moving"]))
        else:
            t3 = "<b>T3:</b> none — bit-exact T1/T2 only (no external label source)"
        if d.get("accepted"):
            state = "<b>Faithfulness (F):</b> %d true causes at the analysis frame — scorable" % (d["n_causes"] or 0)
            scls = "ok"
        elif d.get("accepted") is False:
            state = "<b>Faithfulness (F):</b> too few strong causes at this frame — held out of scoring"
            scls = "na"
        else:
            state = "<b>Faithfulness (F):</b> not in the shared testbed"
            scls = "na"
        poslabs = [c for c in d.get("position_labels", []) if is_pos(c)]
        if d.get("position_regime"):
            pl = (" — e.g. <code>%s</code>" % esc(poslabs[0])) if poslabs else ""
            posrow = '<li class="ok"><b>Position regime:</b> yes%s</li>' % pl
        elif d["labeled"]:
            posrow = '<li class="mid"><b>Position regime:</b> no moving tracked sprite at this frame</li>'
        else:
            posrow = ""
        excluded = d["labeled"] and not d.get("scored", True)
        exbadge = ('<span class="ob na">excluded</span>' if excluded
                   else '<span class="ob ok">scored</span>' if d.get("scored") else '')
        exrow = ('<li class="na"><b>Excluded from the scored battery:</b> %s</li>'
                 % esc(d.get("excluded_reason", ""))) if excluded else ""
        # Per-game results detail page (only for the 42 scored games).
        if g in SITE["games"]:
            thumb = '<a href="g_%s.html">%s</a>' % (g, thumb)
            resrow = ('<li class="ok"><b><a href="g_%s.html">Per-game results →</a></b> '
                      'every XAI method\'s faithfulness on this ROM</li>' % g)
        else:
            resrow = ""
        cards.append(
            '<div class="gtcard%s">'
            '<div class="gtimg">%s</div>'
            '<div class="gtbody"><h4>%s <span class="ob %s">%s</span>%s</h4><ul>'
            '<li class="%s">%s</li><li>%s</li>%s%s%s</ul></div></div>'
            % (" excluded" if excluded else "", thumb, esc(disp(g)), ocls, esc(obadge),
               exbadge, scls, state, t3, posrow, exrow, resrow))

    style = """<style>
.gtprose{max-width:52rem}
.gtprose h3{margin-top:1.6rem}
.gtdefs{display:grid;gap:.7rem;margin:1rem 0}
.gtdefs .d{border-left:3px solid var(--accent);padding:.5rem .9rem;background:rgba(127,127,127,.06)}
.gtcounts{display:flex;flex-wrap:wrap;gap:.6rem;margin:1rem 0}
.gtcounts .c{background:rgba(127,127,127,.10);border-radius:.5rem;padding:.5rem .8rem}
.gtcounts .c b{font-size:1.3rem;display:block}
.gtgrid{display:grid;grid-template-columns:repeat(auto-fill,minmax(300px,1fr));gap:1rem;margin-top:1rem}
.gtcard{border:1px solid rgba(127,127,127,.25);border-radius:.6rem;overflow:hidden;display:flex;flex-direction:column;background:rgba(127,127,127,.04)}
.gtimg{background:#000;aspect-ratio:4/3;display:flex;align-items:center;justify-content:center}
.gtimg img{width:100%;height:100%;object-fit:fill;image-rendering:pixelated}
.gtimg .noimg{color:#888;font-size:.85rem}
.gtbody{padding:.6rem .8rem}
.gtbody h4{margin:.1rem 0 .5rem;display:flex;align-items:center;gap:.5rem;flex-wrap:wrap}
.gtbody ul{margin:0;padding-left:0;list-style:none;font-size:.86rem;line-height:1.45}
.gtbody li{padding:.12rem 0}
.gtbody li.ok{color:var(--ok,#2e7d32)}
.gtbody li.na{color:var(--bad,#b23b3b)}
.gtbody li.mid{color:#8a6d1f}
.ob{font-size:.68rem;font-weight:600;padding:.12rem .45rem;border-radius:.7rem;border:1px solid}
.ob.ok{color:#2e7d32;border-color:#2e7d3255}
.ob.mid{color:#8a6d1f;border-color:#8a6d1f55}
.ob.na{color:#b23b3b;border-color:#b23b3b55}
.gtcard.excluded{opacity:.6;filter:grayscale(.45)}
</style>"""

    intro = """
<header class="hero"><div class="wrap">
  <h1>Ground Truth ROMs</h1>
  <p class="lead">Explainable-AI methods are usually impossible to check: nobody knows the true
  inner workings of a deep network, so an explanation can be convincing and wrong with no way to
  tell. We swap in a 1977 Atari&nbsp;2600 game console instead — a real, complex computer whose
  every wire and byte is known. For any game we can compute the <em>true</em> cause of any pixel
  by literally changing a byte and re-running the machine bit-for-bit. That true answer is the
  ground truth every method is graded against. This page lists, game by game, what ground truth
  we have and where it comes from.</p>
</div></header>

<section><div class="wrap gtprose">
  <h2>Three kinds of ground truth: T1, T2, T3</h2>
  <p>Not all ground truth is the same. We separate what the machine can tell us by itself from
  what only a human can supply.</p>
  <div class="gtdefs">
    <div class="d"><b>T1 &mdash; the causal map (what actually drives the picture).</b> Take one
    memory byte, change its value, re-run the console bit-for-bit, and measure how the screen
    changes. Do that for every candidate byte and you have the exact list of true causes of any
    output. Nothing external is needed &mdash; the machine answers for itself. <b>Available for all
    64 games.</b></div>
    <div class="d"><b>T2 &mdash; the wiring (which part reads or writes which).</b> The program&rsquo;s
    read/write data-flow graph, read straight off the machine: which registers and memory cells
    feed which others. Also exact, also <b>all 64 games.</b></div>
    <div class="d"><b>T3 &mdash; the human meaning (&ldquo;this byte is the ball&rsquo;s x-position&rdquo;).</b>
    This is different in kind. The <em>name</em> of a byte is not inside the machine; it is a human
    fact about what the game <em>means</em>. We import names from two public projects and then
    <b>verify each one causally</b> &mdash; set the byte, re-render, and confirm the named object
    really moves where predicted. We never invent a meaning; we only confirm a supplied one.
    <b>T3 exists for 54 of the 64 games.</b></div>
  </div>

  <h2>How we grade an explanation: F, S, M</h2>
  <p>An explanation is not &ldquo;right&rdquo; just because it looks convincing. We ask three
  separate things, and an explanation only counts as right when it clears all three.</p>
  <div class="gtdefs">
    <div class="d"><b>F &mdash; Faithfulness: does it name the real causes?</b> We compare what the
    method highlights against T1&rsquo;s true causal list. High F means it points at the bytes that
    genuinely drive the output, not at bytes that merely look related.</div>
    <div class="d"><b>S &mdash; Sufficiency: could you rebuild the behaviour from it?</b> A real
    explanation should predict what happens under changes it has not seen. We test it on held-out
    interventions. High S means it captured the mechanism, not just a single snapshot.</div>
    <div class="d"><b>M &mdash; Minimality: is it the <em>smallest</em> true set?</b> Listing every
    byte is perfectly faithful but useless. M rewards naming just the handful of bytes that truly
    matter. &ldquo;Record everything&rdquo; scores near zero on M.</div>
  </div>
  <p>On this machine all three are computed against the oracle (T1/T2), never against another
  method &mdash; which is what keeps the grade honest. The per-method F/S/M scores live on the
  <a href="methods.html">P2 Methods</a> page; this page shows, per game, what those measures
  <em>can</em> be computed against.</p>

  <h2>Where the labels come from</h2>
  <p>The T3 names are external, so we are explicit about their source. We import from
  <b>AtariARI</b> (Anand et al., 2019 &mdash; RAM annotations for 22 games) and <b>OCAtari</b>
  (Delfosse et al., 2024 &mdash; 54 games, with the render-time offset correction that aligns a RAM
  coordinate to where the sprite is actually drawn). Every label is then verified on our bit-exact
  machine before use, so a name is only kept if changing that byte demonstrably moves the named
  object. A method that &ldquo;matches&rdquo; a label is therefore aligning to a meaning we supplied
  &mdash; it did not discover it.</p>
</div></section>

<section><div class="wrap">
  <h2>Per-game ground truth</h2>
  <p class="sub">All 64 bit-exact ROMs (54 carry a T3 label, 10 are T1/T2 only), ordered by how much
  ground truth the shared analysis frame supports (position-regime games first). Screenshots are the actual analysis frame
  the ground truth is computed on. Colour: <span style="color:#2e7d32">green</span> = available,
  <span style="color:#8a6d1f">amber</span> = present but limited at this frame,
  <span style="color:#b23b3b">red</span> = not available. The 10 games with no external label carry
  exact T1/T2 ground truth but are held out of the label-dependent (T3) study.</p>
  <p>Of the 54 labelled ROMs, <b>42 make up the scored battery</b>; the other 12 are <b>excluded</b>
  (dimmed and tagged below). We exclude a game for one of two honest reasons. Eight <b>fail the
  cause-density gate</b>: at the shared frame the chosen output has almost no true causes, so there is
  nothing for a method to be right or wrong about. Four have <b>no sprite that moves under
  intervention</b> &mdash; their verified labels are static things like a score counter, so there is no
  position for a position method to recover; three games fail both tests. Running interpretability
  methods on such a frame cannot measure faithfulness &mdash; it would only add noise to the leaderboard
  &mdash; so we leave those games out of scoring while keeping their exact T1/T2 ground truth on record.
  Every game in the scored battery, by contrast, both passes the gate and carries a moving sprite, so it
  contributes to the all-regime and the position regime alike.</p>
"""

    counts = (
        '<div class="gtcounts">'
        '<div class="c"><b>64</b>bit-exact ROMs (T1/T2)</div>'
        '<div class="c"><b>%d</b>carry a T3 label</div>'
        '<div class="c"><b>%d</b>in the scored battery</div>'
        '<div class="c"><b>%d</b>excluded (degenerate / static)</div>'
        '<div class="c"><b>%d</b>in the position regime</div>'
        '</div>' % (len(labeled), len(scored), len(labeled) - len(scored), len(posreg)))

    body = style + intro + counts + ('<div class="gtgrid">%s</div>' % "".join(cards)) + "</div></section>"
    return page("ground_truth.html", "Ground Truth ROMs — UnderstandingVCS", body)


# Family grouping for the causal/intervention vs gradient/correlational split.
_CAUSAL_TRADITIONS = {"causal", "intervention"}
_GRAD_TRADITIONS = {"gradient", "correlational"}


def _family(tradition):
    if tradition in _CAUSAL_TRADITIONS:
        return ("causal", "causal / intervention")
    if tradition in _GRAD_TRADITIONS:
        return ("grad", "gradient / correlational")
    return ("other", tradition or "other")


def build_game_page(game):
    """Per-game ROM detail page: screenshot + ground truth + every method's
    faithfulness on THIS game, sorted by F, with the causal-vs-gradient split
    visible. Every number is read from docs/site_data.json (games[game])."""
    g = SITE["games"][game]
    disp = game_disp(game)
    rel = "assets/groundtruth/%s.png" % game
    has_img = os.path.exists(os.path.join(HERE, "assets", "groundtruth", game + ".png"))
    thumb = ('<a href="%s" target="_blank"><img src="%s" alt="%s screen" '
             'style="width:100%%;aspect-ratio:4/3;object-fit:fill;image-rendering:pixelated"></a>' % (rel, rel, esc(disp))
             if has_img else '<div class="noimg">screenshot pending</div>')

    origin_lab = {"both": "AtariARI + OCAtari", "OCAtari": "OCAtari",
                  "none": "no external label"}.get(g.get("origin"), esc(str(g.get("origin"))))
    gt_rows = [
        ("External label source", esc(origin_lab)),
        ("Verified causal labels", "%s" % g.get("n_verified")),
        ("Labels that move a sprite", "%s" % g.get("n_moving")),
        ("Scorable (enough true causes)", "yes" if g.get("accepted") else "no"),
        ("Position regime", "yes — a moving tracked sprite at this frame"
         if g.get("position_regime") else "no moving tracked sprite at this frame"),
    ]
    gt_html = "".join("<dt>%s</dt><dd>%s</dd>" % (k, v) for k, v in gt_rows)

    # every method's faithfulness on THIS game, sorted by F desc
    pm = g.get("per_method", {})
    ranked = sorted(pm, key=lambda k: -(pm[k]["F"] if pm[k]["F"] is not None else -1))
    rows = []
    for key in ranked:
        d = pm[key]
        m = SITE["methods"].get(key, {})
        fam_cls, fam_lab = _family(m.get("tradition"))
        name = m.get("name", key)
        rows.append(
            '<tr class="fam-%s">'
            '<td data-v="%s"><a href="m_%s.html">%s</a></td>'
            '<td data-v="%s"><span class="ob %s">%s</span></td>'
            '%s%s%s</tr>'
            % (fam_cls, esc(name), key, esc(name),
               esc(fam_lab), {"causal": "ok", "grad": "na", "other": "mid"}[fam_cls], esc(fam_lab),
               _fcell(d.get("F")), _fcell(d.get("F_content")), _fcell(d.get("F_position"))))
    table = ('<table class="tbl sortable"><thead><tr>'
             '<th data-sort="str">Method</th>'
             '<th data-sort="str">Family</th>'
             '<th data-sort="num">F (all)</th>'
             '<th data-sort="num">content-F</th>'
             '<th data-sort="num">position-F</th></tr></thead><tbody>%s</tbody></table>'
             % "".join(rows))

    style = (SORT_CSS + SORT_JS +
             "<style>tr.fam-causal td:first-child{border-left:3px solid #2e7d32}"
             "tr.fam-grad td:first-child{border-left:3px solid #b23b3b}"
             "tr.fam-other td:first-child{border-left:3px solid #8a6d1f}"
             ".gtimg{background:#000;max-width:520px;border-radius:.5rem;overflow:hidden}</style>")

    body = style + """
<header class="hero"><div class="wrap">
  <span class="venue" style="color:var(--accent-2);font-weight:600">Paper 2 · per-game results</span>
  <h1>%s</h1>
  <p class="lead">The exact ground truth for this ROM and how every interpretability method scores
  against it — one of the <b>%d scored games</b>. Every number is read from
  <a href="%sdocs/site_data.json"><code>site_data.json</code></a> (<code>games.%s</code>).</p>
  <p style="margin-top:10px"><a href="ground_truth.html">← back to the Ground Truth ROMs</a> ·
  <a href="paper2.html">Paper&nbsp;2 audit</a> · <a href="methods.html">method catalogue</a></p>
</div></header>

<section><div class="wrap">
  <div style="display:flex;gap:1.4rem;flex-wrap:wrap;align-items:flex-start">
    <div class="gtimg">%s</div>
    <div style="flex:1;min-width:260px">
      <h2 style="margin-top:0">Ground truth</h2>
      <dl class="meta">%s</dl>
      <p class="caption">The screenshot is the exact analysis frame the ground truth is computed on.
      Labels are imported (AtariARI / OCAtari) then verified causally on the bit-exact machine.</p>
    </div>
  </div>
</div></section>

<section><div class="wrap">
  <h2>Every method's faithfulness on %s</h2>
  <p class="sub">Each XAI / mechanistic-interpretability method's faithfulness on this ROM, sorted by
  F (click a header to re-sort). The left border marks the tradition:
  <span style="color:#2e7d32">green = causal / intervention</span>,
  <span style="color:#b23b3b">red = gradient / correlational</span>,
  <span style="color:#8a6d1f">amber = other</span> — the split the paper's headline turns on.
  F is all-regime; content-F and position-F are the two output regimes (n/a where this game has no
  record for that regime).</p>
  %s
  <p class="caption">Source: <a href="%sdocs/site_data.json"><code>site_data.json</code></a>
  · generated by <a href="%sdocs/gen_site_data.py"><code>gen_site_data.py</code></a> from the
  committed §R records + <code>leaderboard.json</code>.</p>
</div></section>
""" % (esc(disp), SITE["meta"]["scored_games"], BLOB, esc(game),
       thumb, gt_html, esc(disp), table, BLOB, BLOB)
    return page("g_%s.html" % game, "%s — Paper 2 per-game results" % disp, body)


def main():
    outputs = {
        "index.html": build_index(),
        "paper1.html": build_paper(M.PAPER1),
        "paper2.html": build_paper(M.PAPER2),
        "conformance.html": build_conformance(),
        "methods.html": build_methods(),
        "ground_truth.html": build_ground_truth(),
        "provenance.html": build_provenance(),
        "environment.html": build_environment(),
        "reproduce.html": build_reproduce(),
    }
    for meth in M.P2_METHODS:
        outputs["m_%s.html" % meth["key"]] = build_method_page(meth)
    for game in SITE["games"]:
        outputs["g_%s.html" % game] = build_game_page(game)
    for name, content in outputs.items():
        with open(os.path.join(HERE, name), "w") as f:
            f.write(content)
        print("wrote docs/%s (%d bytes)" % (name, len(content)))
    # .nojekyll so GitHub Pages serves our paths verbatim
    open(os.path.join(HERE, ".nojekyll"), "w").close()
    print("built at commit", SHORT)


if __name__ == "__main__":
    main()
